'use strict';
(() => {
 const labels=['减排需求','碳汇覆盖','土地可用','坡度适宜','经济基础','自然潜力'],keys=['carbon','land6','land3','slope','gdp','solar'];
 const benefit=(c,i)=>{const m=model.priorityRevision,v=val(c,keys[i]),span=m.high[i]-m.low[i];if(!valid(v))return null;const z=span?(v-m.low[i])/span:0;return m.directions[i]===-1?1-z:z;};
 const panel=document.createElement('section');panel.id='analysisStudio';panel.className='analysisStudio';panel.hidden=true;
 panel.innerHTML=`<div class="studioHeading"><div><span class="eyebrow">FROM EVIDENCE TO CHOICE / 研究筛选台</span><h2>把一张地图，变成一份有依据的候选清单。</h2><p>设定资源与土地条件，查看分布，再带入县域对照。筛选不修改研究模型得分。</p></div><button id="closeStudio" aria-label="收起研究筛选台">收起 ×</button></div><div class="studioFilters"><label>辐射指数至少 <output id="sunOutput">0.40</output><input id="sunFilter" type="range" min="0" max="1" step="0.01" value="0.4"></label><label>土地可用程度至少 <output id="landOutput">40%</output><input id="landFilter" type="range" min="0" max="1" step="0.01" value="0.4"></label><label>保护区覆盖至多 <output id="reserveOutput">5%</output><input id="reserveFilter" type="range" min="0" max="1" step="0.01" value="0.05"></label><div class="studioSwitch"><label><input id="applyCandidates" type="checkbox">在地图上突出候选县</label><button id="clearBrush">清除框选</button><button id="resetStudio">恢复筛选默认值</button></div></div><p class="studioDefinition">土地可用程度 = 1 − 不可用土地占比。阈值由使用者设定，不是法定选址标准；县域保护区比例较低也不能证明具体地块可开发。</p><div class="studioStats" id="studioStats" aria-live="polite"></div><div class="studioCharts"><article><div class="chartHeading"><h3>资源 × 土地：在分布中寻找候选</h3><span>拖动框选 · 点选县域</span></div><svg id="resourcePlot" viewBox="0 0 660 370" aria-label="县域太阳辐射与土地可用程度散点图，可拖动框选"></svg><p id="brushStatus" class="studioDefinition"></p></article><article><div class="chartHeading"><h3>省域画像：三个共同刻度</h3><span>点击省名下钻</span></div><div id="provinceProfiles"></div><p class="studioDefinition">辐射、土地可用程度为有效县均值；高优先级为5级县数占比。均使用0–1刻度，不表示同一物理单位。</p></article></div><div class="candidateHeading"><h3>候选县清单</h3><div><button id="exportCandidates">导出全部候选 CSV ↓</button><button id="backToMap">回到地图 ↗</button></div></div><p id="candidateNote" class="studioDefinition"></p><div class="candidateTable tableWrap"><table><thead><tr><th>县域</th><th>辐射</th><th>土地可用</th><th>保护区</th><th>模型得分</th><th>优先级</th><th>加入对照</th></tr></thead><tbody id="candidateRows"></tbody></table></div>`;
 $('atlas').after(panel);
 const launch=document.createElement('button');launch.id='openStudio';launch.className='studioLaunch';launch.textContent='候选分布与清单 ↗';document.querySelector('.overlayControls').prepend(launch);
 const ribbon=document.createElement('section');ribbon.className='mapFilterRibbon';ribbon.setAttribute('aria-label','县域候选筛选条件');ribbon.innerHTML='<div class="filterRibbonHeading"><strong>筛选条件 · 拖动滑块</strong><span>只筛选候选县，不改变地图指标与研究等级</span></div><div class="visibleSliders"></div><div class="filterRibbonFooter"><label><input id="mapCandidateToggle" type="checkbox">突出满足条件的县域</label><span id="mapFilterCount" aria-live="polite"></span></div>';
 document.querySelector('.overlayControls').before(ribbon);
 for(const id of ['sunFilter','landFilter','reserveFilter'])ribbon.querySelector('.visibleSliders').append($(id).closest('label'));
 $('mapCandidateToggle').onchange=()=>{$('applyCandidates').checked=$('mapCandidateToggle').checked;refresh(true);};
 let brush=null,filtered=[],eligible=[],cacheKey='',commitKey='',maskKey='',frame=0,commitTimer=0,lastPreview=0,poolKey='',profilesKey='',tableKey='',plotKey='',currentFilter=null;
 const dots=new Map();let goldIds=new Set(),zone=null,brushOutline=null;
 const perf=window.ATLAS_STUDIO_PERF={updates:0,maxMs:0,lastMs:0,pointBuilds:0};
 const config=()=>({sun:+$('sunFilter').value,land:+$('landFilter').value,reserve:+$('reserveFilter').value});
 const matches=c=>{const f=currentFilter;return c.radiation>=f.sun&&1-c.land3>=f.land&&c.protected<=f.reserve&&(!brush||(c.radiation>=brush.x0&&c.radiation<=brush.x1&&1-c.land3>=brush.y0&&1-c.land3<=brush.y1));};
 const scope=()=>selectedProv&&mode==='province'?selectedProv.id:pid;
 function calculate(){currentFilter=config();const id=scope(),key=JSON.stringify([id,version]);if(key!==poolKey){poolKey=key;eligible=counties.filter(c=>(!id||c.pid===id)&&valid(c.radiation)&&valid(c.land3)&&valid(c.protected)&&valid(val(c,'score'))).sort((a,b)=>val(b,'score')-val(a,'score')||a.id.localeCompare(b.id));}filtered=eligible.filter(matches);}
 function applyMask(){const key=JSON.stringify([mapKey,scope(),config(),brush,$('applyCandidates').checked]);if(key===maskKey)return;maskKey=key;const ids=new Set(filtered.map(c=>c.id));for(const p of $('regions').children){const muted=$('applyCandidates').checked&&mode==='county'&&!ids.has(p.dataset.id);if(p.classList.contains('candidateMuted')!==muted)p.classList.toggle('candidateMuted',muted);}}
 function drawProfiles(){const id=scope(),key=JSON.stringify([id,version]);if(key===profilesKey)return;profilesKey=key;let list=id?provinces.filter(p=>p.id===id):['620000','520000','650000','150000','540000','370000'].map(id=>provinces.find(p=>p.id===id)).filter(Boolean);$('provinceProfiles').innerHTML=list.map(p=>{const members=provRows(p),values=[avg(members,'radiation'),valid(avg(members,'land3'))?1-avg(members,'land3'):null,pval(p,'priority')];return '<button class="provinceProfile" data-province="'+p.id+'"><strong>'+esc(p.name)+'</strong><div>'+values.map((v,i)=>'<span><small>'+['辐射','土地可用','5级占比'][i]+'</small><i><b style="width:'+((v??0)*100)+'%;background:'+['#ffb454','#80bcb0','#d3ba7b'][i]+'"></b></i><em>'+(valid(v)?(i? (v*100).toFixed(1)+'%':v.toFixed(3)):'缺失')+'</em></span>').join('')+'</div></button>';}).join('');for(const b of $('provinceProfiles').querySelectorAll('button'))b.onclick=()=>{enterProvince(b.dataset.province);refresh(true);};}
 function drawPlot(){const chart=$('resourcePlot'),x=v=>52+v*575,y=v=>322-v*278;
  if(plotKey!==poolKey){plotKey=poolKey;dots.clear();goldIds.clear();const fragment=document.createDocumentFragment();
   for(let i=0;i<=5;i++){const v=i/5;fragment.append(svg('path',{d:`M52 ${y(v)}H627 M${x(v)} 44V322`,class:'plotGrid'}),svg('text',{x:x(v),y:344,'text-anchor':'middle',class:'plotTick'},v.toFixed(1)),svg('text',{x:44,y:y(v)+4,'text-anchor':'end',class:'plotTick'},Math.round(v*100)+'%'));}
   fragment.append(svg('text',{x:52,y:22,class:'axisLabel'},'土地可用程度 ↑'),svg('text',{x:627,y:365,'text-anchor':'end',class:'axisLabel'},'太阳辐射指数 →'));
   zone=svg('rect',{class:'candidateZone'});fragment.append(zone);
   for(const c of eligible){const dot=svg('circle',{cx:x(c.radiation),cy:y(1-c.land3),class:'plotDot',r:1.7,tabindex:-1,role:'button','aria-label':c.name+'，辐射'+c.radiation.toFixed(3)+'，土地可用'+((1-c.land3)*100).toFixed(1)+'%'});dot.dataset.county=c.id;dot.append(svg('title',{},c.province+' · '+c.name+' / 辐射 '+c.radiation.toFixed(3)+' / 土地可用 '+((1-c.land3)*100).toFixed(1)+'%'));dots.set(c.id,dot);fragment.append(dot);}
   brushOutline=svg('rect',{class:'brushRect','pointer-events':'none'});brushOutline.style.display='none';fragment.append(brushOutline);chart.replaceChildren(fragment);perf.pointBuilds++;
  }
  const f=currentFilter;zone.setAttribute('x',x(f.sun));zone.setAttribute('y',44);zone.setAttribute('width',(1-f.sun)*575);zone.setAttribute('height',(1-f.land)*278);
  const next=new Set(filtered.map(c=>c.id));
  for(const id of goldIds)if(!next.has(id)){const dot=dots.get(id);dot.classList.remove('plotMatch');dot.setAttribute('tabindex',-1);}
  for(const id of next)if(!goldIds.has(id)){const dot=dots.get(id);dot.classList.add('plotMatch');dot.setAttribute('tabindex',0);}
  goldIds=next;brushOutline.style.display=brush?'':'none';if(brush){brushOutline.setAttribute('x',x(brush.x0));brushOutline.setAttribute('y',y(brush.y1));brushOutline.setAttribute('width',(brush.x1-brush.x0)*575);brushOutline.setAttribute('height',(brush.y1-brush.y0)*278);}
 }
 function updateReadouts(){$('sunOutput').textContent=(+$('sunFilter').value).toFixed(2);$('landOutput').textContent=Math.round(+$('landFilter').value*100)+'%';$('reserveOutput').textContent=Math.round(+$('reserveFilter').value*100)+'%';}
 function refresh(force=false,preview=false){const began=performance.now();if(!preview){cancelAnimationFrame(frame);frame=0;clearTimeout(commitTimer);}const key=JSON.stringify([scope(),version,config(),brush]);if(!force&&key===cacheKey&&(preview||key===commitKey)){if(!preview)applyMask();return;}calculate();if(!preview)applyMask();cacheKey=key;if(!preview)commitKey=key;
  $('mapCandidateToggle').checked=$('applyCandidates').checked;
  $('mapFilterCount').textContent=filtered.length+' / '+eligible.length+' 县满足条件'+($('applyCandidates').checked?' · 淡化区域为未入选，并非数据缺失':' · 地图仍显示全部县域');
  if(panel.hidden){updateReadouts();return;}
  updateReadouts();
  const coverage=scope()?provRows(provinces.find(p=>p.id===scope())):counties;
  $('studioStats').innerHTML=[['当前范围',scope()?provinces.find(p=>p.id===scope()).name:'全国'],['可参与筛选',eligible.length+' 县'],['满足条件',filtered.length+' 县'],['平均协调度',fmt(avg(filtered,'coord'))]].map(([k,v])=>'<div><small>'+k+'</small><strong>'+v+'</strong></div>').join('');
  $('brushStatus').textContent=brush?'框选范围：辐射 '+brush.x0.toFixed(2)+'–'+brush.x1.toFixed(2)+'，土地可用 '+(brush.y0*100).toFixed(0)+'–'+(brush.y1*100).toFixed(0)+'%。':'无框选限制；金色点满足当前全部筛选条件，背景矩形仅表示辐射与土地阈值。';
  $('candidateNote').textContent='共 '+filtered.length+' 个候选，按原研究模型得分降序；页面显示前30个，导出包含全部。当前范围 '+coverage.length+' 县，缺少筛选指标或模型结果的 '+(coverage.length-eligible.length)+' 县未参与。';
  const nextTableKey=JSON.stringify([version,...filtered.slice(0,30).map(c=>c.id)]);if(!preview&&nextTableKey!==tableKey){tableKey=nextTableKey;$('candidateRows').innerHTML=filtered.slice(0,30).map(c=>'<tr><td><button data-locate="'+c.id+'">'+esc(c.name)+'</button><small>'+esc(c.province)+'</small></td><td>'+c.radiation.toFixed(3)+'</td><td>'+((1-c.land3)*100).toFixed(1)+'%</td><td>'+(c.protected*100).toFixed(1)+'%</td><td>'+fmt(val(c,'score'))+'</td><td>'+val(c,'priority')+'级</td><td><button data-a="'+c.id+'">A</button> <button data-b="'+c.id+'">B</button></td></tr>').join('')||'<tr><td colspan="7" class="emptyCandidates">没有满足条件的县域，可放宽阈值或清除框选。</td></tr>';
  for(const b of $('candidateRows').querySelectorAll('button'))b.onclick=()=>{if(b.dataset.locate){selectCounty(counties.find(c=>c.id===b.dataset.locate));$('atlas').scrollIntoView({behavior:'smooth'});}else{const role=b.dataset.a?'A':'B';$('compare'+role).value=b.dataset.a||b.dataset.b;renderComparison();b.textContent='已加入 '+role;}};
  }
  $('candidateRows').closest('table').setAttribute('aria-busy',String(preview));drawProfiles();drawPlot();$('exportCandidates').disabled=!filtered.length;perf.lastMs=performance.now()-began;perf.maxMs=Math.max(perf.maxMs,perf.lastMs);perf.updates++;

 }
 const mapBefore=renderMap;renderMap=function(){mapBefore();refresh();};
 const detailBefore=renderDetail;const profile=document.createElement('section');profile.id='countyProfile';$('detail').after(profile);
 renderDetail=function(){detailBefore();profile.hidden=!selected;if(!selected)return;profile.innerHTML='<div class="profileTitle"><span>六项评分剖面</span><small>高值表示评分更有利</small></div>'+labels.map((label,i)=>{const v=benefit(selected,i);return '<div class="scoreProfile"><span>'+label+'</span><i><b style="width:'+((v??0)*100)+'%"></b></i><strong>'+fmt(v)+'</strong></div>';}).join('')+'<p>土地已反向处理；高碳强度表达减排需求。各项权重1/6，不把协调度重复计入。</p>'+(selected.recoveryNote?'<p>'+esc(selected.recoveryNote)+'</p>':'');};
 launch.onclick=()=>{panel.hidden=!panel.hidden;launch.setAttribute('aria-expanded',String(!panel.hidden));if(!panel.hidden){refresh(true);panel.scrollIntoView({behavior:'smooth',block:'start'});}};$('closeStudio').onclick=()=>{panel.hidden=true;launch.setAttribute('aria-expanded','false');$('atlas').scrollIntoView({behavior:'smooth'});};launch.setAttribute('aria-expanded','false');launch.setAttribute('aria-controls','analysisStudio');
 for(const id of ['sunFilter','landFilter','reserveFilter']){
  $(id).oninput=()=>{updateReadouts();clearTimeout(commitTimer);commitTimer=setTimeout(()=>refresh(true),140);if(!frame){const preview=now=>{if(now-lastPreview<50){frame=requestAnimationFrame(preview);return;}frame=0;lastPreview=now;refresh(false,true);};frame=requestAnimationFrame(preview);}};
  $(id).onchange=()=>refresh(true);$(id).onblur=()=>refresh();
 }
 $('applyCandidates').onchange=()=>refresh(true);
 $('clearBrush').onclick=()=>{brush=null;refresh(true);};$('resetStudio').onclick=()=>{brush=null;$('sunFilter').value=.4;$('landFilter').value=.4;$('reserveFilter').value=.05;$('applyCandidates').checked=false;refresh(true);};$('backToMap').onclick=()=>$('atlas').scrollIntoView({behavior:'smooth'});
 $('exportCandidates').onclick=()=>{refresh(true);const f=config(),quote=v=>'"'+String(v??'').replaceAll('"','""')+'"',header=['县代码','县名','省份','辐射指数','土地可用程度','不可用土地占比','保护区覆盖','综合得分','优先级','协调度','辐射下限','土地可用下限','保护区上限','框选范围'];const lines=filtered.map(c=>[c.id,c.name,c.province,c.radiation,1-c.land3,c.land3,c.protected,val(c,'score'),val(c,'priority'),val(c,'coord'),f.sun,f.land,f.reserve,brush?JSON.stringify(brush):'无框选'].map(quote).join(','));const link=document.createElement('a'),url=URL.createObjectURL(new Blob(['\ufeff'+header.join(',')+'\r\n'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}));link.href=url;link.download='逐光-候选县清单.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 $('resourcePlot').onkeydown=e=>{if(e.key==='Enter'&&e.target.dataset.county){selectCounty(counties.find(c=>c.id===e.target.dataset.county));$('atlas').scrollIntoView({behavior:'smooth'});}};
 let start=null,rectangle=null;const chart=$('resourcePlot'),point=e=>{const p=chart.createSVGPoint();p.x=e.clientX;p.y=e.clientY;const q=p.matrixTransform(chart.getScreenCTM().inverse());return {x:Math.max(52,Math.min(627,q.x)),y:Math.max(44,Math.min(322,q.y))};};
 chart.onpointerdown=e=>{if(e.button!==0)return;start={...point(e),county:e.target.closest('circle')?.dataset.county};rectangle=null;chart.setPointerCapture(e.pointerId);};chart.onpointermove=e=>{if(!start)return;const end=point(e);if(Math.hypot(end.x-start.x,end.y-start.y)<8&&!rectangle)return;if(!rectangle){rectangle=svg('rect',{class:'brushRect','pointer-events':'none'});chart.append(rectangle);}rectangle.setAttribute('x',Math.min(start.x,end.x));rectangle.setAttribute('y',Math.min(start.y,end.y));rectangle.setAttribute('width',Math.abs(end.x-start.x));rectangle.setAttribute('height',Math.abs(end.y-start.y));};
 chart.onpointerup=e=>{if(!start)return;const end=point(e);if(rectangle){brush={x0:(Math.min(start.x,end.x)-52)/575,x1:(Math.max(start.x,end.x)-52)/575,y0:1-(Math.max(start.y,end.y)-44)/278,y1:1-(Math.min(start.y,end.y)-44)/278};refresh(true);}else if(start.county){selectCounty(counties.find(c=>c.id===start.county));$('atlas').scrollIntoView({behavior:'smooth'});}start=null;rectangle=null;};chart.onpointercancel=()=>{start=null;rectangle?.remove();rectangle=null;};
 const baseline=document.querySelector('.intro p');baseline.textContent='比较县域光伏资源与生态约束，识别值得优先研究的地区。点击图层看指标，拖动滑块筛候选，点击县域看依据。';
 const groups=[1,2,3,4,5].map(g=>counties.filter(c=>val(c,'priority')===g).length),total=groups.reduce((a,b)=>a+b,0),largest=groups.indexOf(Math.max(...groups));
 document.querySelector('.distribution>.subtle').textContent='全国五分位分组中，'+(largest+1)+'级占'+(groups[largest]/total*100).toFixed(1)+'%；每级约20%，同分不拆级；请同时查看连续得分与评分剖面。地区筛选不重新划级。';
 refresh(true);renderDetail();window.dispatchEvent(new Event('resize'));window.ATLAS_STUDIO_READY=true;
})();

// ONLINE_DASHBOARD_LOADER
const dashboardScript=document.createElement('script');dashboardScript.src='dashboard.js?v=17';document.body.append(dashboardScript);
