'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg';
const {counties,provinces,audit,model,reserves}=window.ATLAS;
const colors=['#294d61','#397580','#72a79e','#d3ba7b','#ffb454'];
const defs={priority:['开发优先级','全国得分范围五等距 · 5 为最高','level'],score:['综合得分','六指标等权欧氏 TOPSIS','index'],coord:['耦合协调度','县域内两系统协调 D','index'],solar:['自然光伏潜力','综合自然条件与可开发规模 · 指数','index'],radiation:['太阳辐射','2016 年 · 归一化','index'],slope:['土地坡度','25°阈值处理后的源表指数','index'],land3:['不可用土地占比','数值越大，土地约束越强 · 低值更有利','percent'],gdp:['GDP 经济指数','统计值优先 · 缺失灯光补估','index'],carbonTotal:['碳排放总量','吨 CO₂ · 2023 / 部分 2022','total'],land6:['碳汇覆盖占比','林地 / 草地 / 湿地 / 灌木','percent'],protected:['保护区覆盖占比','所给保护区与县域相交','percent']};
let protectedView='footprint';
let metric='priority',mode='county',pid='',selected=null,selectedProv=null,version='hybrid',view=[-12,-5,900,850],drag=null,dragMoved=false;
const valid=v=>typeof v==='number'&&Number.isFinite(v),fmt=v=>valid(v)?v.toFixed(3):'暂无数据',esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const versionName=()=>({hybrid:'统计优先·修订评分版',revised:'全灯光估计实验版',original:'原论文版'}[version]);
const val=(c,k)=>version!=='original'&&['gdp','coord','score','priority','grade'].includes(k)?(version==='hybrid'?c.v3:c.v2)[k]:c[k];
const areaRows=()=>counties.filter(c=>!pid||c.pid===pid);
const rows=()=>areaRows().filter(c=>valid(val(c,'score')));
const avg=(a,k)=>{let v=a.map(c=>val(c,k)).filter(valid);return v.length?v.reduce((s,c)=>s+c,0)/v.length:null;};
const provinceRows=new Map(provinces.map(p=>[p.id,counties.filter(c=>c.pid===p.id)]));
const provRows=p=>provinceRows.get(p.id)||[];
function pval(p,k){let a=provRows(p);if(isTotal(k)){const v=a.map(c=>c[k]).filter(valid);return v.length?v.reduce((s,x)=>s+x,0):null;}if(k==='priority'){a=a.filter(c=>valid(val(c,'priority')));return a.length?a.filter(c=>val(c,'priority')===5).length/a.length:null;}if(k==='protected'){let total=a.reduce((s,c)=>s+c.area_km2,0);return total?a.reduce((s,c)=>s+c.protected_km2,0)/total:null;}return avg(a,k);}
const mapValue=c=>mode==='county'?val(c,metric):pval(c,metric);
const isTotal=k=>k==='carbonTotal';
const totalUnit=k=>k==='carbonTotal'?'吨 CO₂':'万千瓦时';
function totalCoverage(list,k){return list.filter(c=>valid(c[k])).length+'/'+list.length;}
function metricNote(c,k){if(isTotal(k))return valid(c[k])?c[k+'Year']+' 年统计总量 · '+totalUnit(k)+'；地图和对照展示总量，研究排名与关联采用六指标等权修订模型，总量不直接进入排名。':'原表未提供有效正值，保留缺失，不以 0 或 GDP 估算替代。';return '';}
function display(v,k=metric,province=false){if(!valid(v))return '暂无数据';if(isTotal(k))return v.toLocaleString('zh-CN',{maximumFractionDigits:1})+' '+totalUnit(k);if(k==='priority')return province?(v*100).toFixed(1)+'%':v+' 级';return defs[k][2]==='percent'?(v*100).toFixed(1)+'%':v.toFixed(3);}
let thresholds=[];
function scaleSetup(){if(metric==='protected'){thresholds=[.01,.05,.2,.5];return;}if(metric==='priority'&&mode==='county'){thresholds=[1,2,3,4];return;}let vs=(mode==='county'?counties:provinces).map(mapValue).filter(valid).sort((a,b)=>a-b);thresholds=[.2,.4,.6,.8].map(q=>vs[Math.min(vs.length-1,Math.floor(q*vs.length))]??0);}
function fill(v){if(metric==='protected'&&protectedView==='footprint')return '#182b39';if(metric==='protected'&&v===0)return '#263541';if(!valid(v))return 'url(#missing)';if(metric==='priority'&&mode==='county')return colors[v-1];const i=thresholds.filter(t=>v>t).length;return metric==='land3'?colors[4-i]:colors[i];}
function svg(tag,attrs,text){const e=document.createElementNS(NS,tag);Object.entries(attrs||{}).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;}
$('metrics').innerHTML=Object.entries(defs).map(([k,d],i)=>`<button data-metric="${k}" class="${k===metric?'active':''}" title="${esc(d[1])}"><em>${String(i+1).padStart(2,'0')}</em><span>${d[0]}</span></button>`).join('');
for(const p of provinces.sort((a,b)=>a.id.localeCompare(b.id))){const o=document.createElement('option');o.value=p.id;o.textContent=p.name;$('province').append(o);}
$('countyList').innerHTML=counties.map(c=>`<option value="${esc(c.name+' '+c.id)}">${esc(c.province+' · '+c.city)}</option>`).join('');
let mapKey='',statsKey='',rankingKey='',reserveBuilt=false;
function syncSelection(){
 const id=mode==='county'?selected?.id:selectedProv?.id;
 const old=$('regions').querySelector('.selected');
 if(old?.dataset.id!==id){old?.classList.remove('selected');if(id)$('regions').querySelector(`[data-id="${id}"]`)?.classList.add('selected');}
 const oldDot=$('scatter').querySelector('.activeDot');
 if(oldDot?.dataset.id!==selected?.id){if(oldDot){oldDot.classList.remove('activeDot');oldDot.setAttribute('r','2.3');oldDot.setAttribute('opacity','.58');}
 if(selected){const dot=$('scatter').querySelector(`[data-id="${selected.id}"]`);if(dot){dot.classList.add('activeDot');dot.setAttribute('r','4');dot.setAttribute('opacity','1');}}}
}
function renderMap(){const key=[mode,pid,metric,version,protectedView].join('|');if(key===mapKey){syncSelection();renderOverlays();return;}mapKey=key;scaleSetup();$('regions').replaceChildren();$('outlines').replaceChildren();$('tooltip').style.display='none';
 for(const c of (mode==='county'?counties:provinces)){const p=svg('path',{d:c.path,fill:fill(mapValue(c)),'fill-rule':'evenodd',class:mode+((mode==='county'?selected?.id:selectedProv?.id)===c.id?' selected':'')});p.dataset.id=c.id;if(pid&&(mode==='county'?c.pid:c.id)!==pid)p.style.opacity='.12';
 p.addEventListener('click',()=>{if(dragMoved)return;if(mode==='province'){selectedProv=c;selected=null;render();fitSelection();}else selectCounty(c);});p.addEventListener('dblclick',()=>{if(mode==='province')enterProvince(c.id);});
 p.addEventListener('pointermove',e=>{if(drag)return;const label=mode==='province'&&metric==='priority'?'最高优先级占比':defs[metric][0];$('tooltip').innerHTML=`<b>${esc(c.name)}</b><br>${label}：${display(mapValue(c),metric,mode==='province')}`;const r=$('map').parentElement.getBoundingClientRect();$('tooltip').style.display='block';$('tooltip').style.left=Math.max(4,Math.min(e.clientX-r.left+14,r.width-218))+'px';$('tooltip').style.top=Math.max(4,Math.min(e.clientY-r.top+10,r.height-75))+'px';});p.addEventListener('pointerleave',()=>$('tooltip').style.display='none');$('regions').append(p);}
 if(mode==='county')for(const p of provinces){const x=svg('path',{d:p.path,class:'outline'});if(pid&&p.id!==pid)x.style.opacity='.12';$('outlines').append(x);}
 $('protectedControls').hidden=metric!=='protected';$('showReserves').disabled=metric==='protected'&&protectedView==='footprint';$('showReserves').closest('label').hidden=metric==='protected'&&protectedView==='footprint';$('showLinks').disabled=metric==='protected';$('showLinks').closest('label').hidden=metric==='protected';
 document.querySelectorAll('[data-protected-view]').forEach(b=>b.classList.toggle('active',b.dataset.protectedView===protectedView));
 $('mapTitle').textContent=mode==='province'&&metric==='priority'?'最高优先级县域占比':defs[metric][0];$('scopeName').textContent=provinces.find(p=>p.id===pid)?.name||'中国 · 全国范围';
 $('mapSubtitle').textContent=(mode==='province'?'单击看关系 · 双击下钻县域':'单击县域看详情 · 拖动及滚轮缩放')+' / '+defs[metric][1];
 $('countyMode').classList.toggle('active',mode==='county');$('provinceMode').classList.toggle('active',mode==='province');
 let labels=metric==='priority'&&mode==='county'?['1 · 优先级最低','2 · 较低','3 · 中等','4 · 较高','5 · 优先级最高']:[`≤${display(thresholds[0],metric,mode==='province')}`,...thresholds.slice(1).map((v,i)=>`${display(thresholds[i],metric,mode==='province')}–${display(v,metric,mode==='province')}`),`>${display(thresholds[3],metric,mode==='province')}`];
 $('legendItems').innerHTML=labels.map((t,i)=>`<span><i style="background:${metric==='land3'?colors[4-i]:colors[i]}"></i>${t}</span>`).join('')+'<span><i class="missingKey"></i>无数据</span>';
 $('legendNote').textContent=metric==='priority'?(mode==='county'?'六指标等权评分；全国得分范围五等距分组，不强制每组占20%，不是工程审批标准。':'5级县域数 / 本省有效县域数；色阶为省级分位点。'):(metric==='protected'&&mode==='province'?'省内相交面积合计 / 县域面积合计。':mode==='province'?'有效县域的算术平均，非省级重新建模。':'全国有效样本分位点着色；更高数值不一定更适宜开发。');
 if(metric==='protected'){
  $('mapTitle').textContent=protectedView==='footprint'?'保护区实际边界':'县域保护区覆盖率';
  $('legendItems').innerHTML=protectedView==='footprint'?'<span><i style="background:#263541"></i>行政区背景</span><span><i style="background:#ffb454"></i>所给保护区范围</span>':['0（未相交）','>0–1%','>1–5%','>5–20%','>20–50%','>50%'].map((label,i)=>'<span><i style="background:'+(['#263541',...colors][i])+'"></i>'+label+'</span>').join('');
  $('legendNote').textContent=protectedView==='footprint'?'仅保护区轮廓内着色。显示几何经过简化；覆盖面积按原始边界计算。':'整县颜色表示保护区面积 / 县域面积，不代表整县都是保护区。固定比例刻度，0 单独显示。';
 }
 if(isTotal(metric))$('legendNote').textContent='统计总量 · '+totalUnit(metric)+'；有效县域 '+totalCoverage(areaRows(),metric)+'。省级为已覆盖县域小计，不等同于完整省级总量。颜色为有效值分位数；高值不等于更适宜开发。';
 renderOverlays();}
function relationFocus(){if(mode==='province')return selectedProv||provinces.find(p=>p.id===pid)||provinces.find(p=>p.id==='630000');return selected||rows().slice().sort((a,b)=>val(b,'score')-val(a,'score'))[0];}
function renderOverlays(){const pg=$('reservesLayer');const show=$('showReserves').checked||(metric==='protected'&&protectedView==='footprint');pg.style.display=show?'':'none';if(show&&!reserves.length){ensureReserves();}if(show&&reserves.length&&!reserveBuilt){const fragment=document.createDocumentFragment();for(const r of reserves)fragment.append(svg('path',{d:r.path,class:'reserveShape','fill-rule':'evenodd'}));pg.append(fragment);reserveBuilt=true;}
 const lg=$('linksLayer'),labels=$('labelsLayer');lg.replaceChildren();labels.replaceChildren();const focus=relationFocus();let edges=[];
 if(($('showLinks').checked&&metric!=='protected')){if(mode==='province'&&!selectedProv&&!pid){let seen=new Set();for(const p of provinces)for(const r of (p.relations[version]||[]).slice(0,2)){const key=[p.id,r.id].sort().join('-');if(!seen.has(key)){seen.add(key);edges.push({from:p,to:provinces.find(x=>x.id===r.id),...r});}}}else if(focus){for(const r of focus.relations[version]||[])edges.push({from:focus,to:(mode==='county'?counties:provinces).find(x=>x.id===r.id),...r});}}
 for(const e of edges){if(!e.to)continue;let [x,y]=e.from.center,[a,b]=e.to.center,dx=a-x,dy=b-y,bend=.16;const d=`M${x},${y}Q${(x+a)/2-dy*bend},${(y+b)/2+dx*bend} ${a},${b}`;lg.append(svg('path',{d,class:'relationGlow',opacity:e.strength*.5}));lg.append(svg('path',{d,class:'relationLine',opacity:.3+.6*e.strength}));for(const c of [e.from,e.to])lg.append(svg('circle',{cx:c.center[0],cy:c.center[1],r:0,'data-region':c.id,class:'relationNode'}));}
 if(focus&&($('showLinks').checked&&metric!=='protected')&&edges.length){let nodes=(mode==='county'?selected:selectedProv)?[focus]:[];for(const c of nodes){const t=svg('text',{x:c.center[0],y:c.center[1],class:'mapLabel'},c.name.replace('维吾尔自治区','').replace('回族自治区','').replace('壮族自治区','').replace('省',''));labels.append(t);}}
 sizeRelationMarks();$('linkStatus').textContent=($('showLinks').checked&&metric!=='protected')?`${edges.length} 条计算关系 · ${versionName()}`:(metric==='protected'?'保护区视图 · 隐藏近邻连线以免混淆':'关系图层已关闭');}
function indicator(label,v,percent=false){return `<div class="indicator"><div><span>${label}</span><b>${percent?(valid(v)?(v*100).toFixed(1)+'%':'暂无数据'):fmt(v)}</b></div><div class="track"><i style="width:${valid(v)?Math.max(0,Math.min(1,v))*100:0}%"></i></div></div>`;}
function renderDetail(){const a=rows();let html='';
 if(mode==='county'&&selected){const c=selected;html=`<p class="detailLocation">${esc(c.province)} / ${esc(c.city)} · ${c.id}</p><h2 class="detailTitle">${esc(c.name)}</h2><span class="badge">${display(val(c,'priority'),'priority')}优先级 · ${esc(val(c,'grade')||'暂无协调等级')}</span><div class="selectedMetric"><span>${defs[metric][0]}</span><strong>${display(val(c,metric))}</strong></div><div class="detailScore"><div><strong>${fmt(val(c,'score'))}</strong><span>综合得分</span></div><div><strong>${fmt(val(c,'coord'))}</strong><span>耦合协调度</span></div></div>${indicator('太阳辐射指数',c.radiation)}${indicator('碳汇覆盖占比',c.land6,true)}${indicator('保护区覆盖占比',c.protected,true)}<p class="detailNote">相交保护区 ${c.reserve_count} 个 · 相交面积 ${c.protected_km2.toFixed(1)} km²</p>${version!=='original'?`<div class="gdpEstimate"><span>${version==='hybrid'?'当前采用 GDP':'全灯光 GDP 估计'}</span><b>${valid(version==='hybrid'?c.gdpHybrid:c.gdpEstimate)?(version==='hybrid'?c.gdpHybrid:c.gdpEstimate).toFixed(1):'—'} <small>亿元</small></b><small>${esc(version==='hybrid'?c.gdpHybridSource:c.gdpKind||'输入不足')}</small></div>`:''}<p class="detailNote">${metric==='land3'?'不可用土地占比越大，土地约束越强；评分按负向处理。':metric==='slope'?'这是阈值处理后的源表指数，不是平均坡度角。':isTotal(metric)?metricNote(c,metric):'采用统计 GDP 优先、灯光补缺方案；详情标明 GDP 来源。'}</p>`;
 }else{const p=selectedProv||provinces.find(p=>p.id===pid),r=p?provRows(p).filter(c=>valid(val(c,'score'))):a;html=`<p class="detailLocation">${p?'省内有效县域汇总':'全国有效样本'}</p><h2 class="detailTitle">${p?esc(p.name):'全国概览'}</h2><span class="badge">${r.length.toLocaleString()} 个有效县域</span><div class="detailScore"><div><strong>${fmt(avg(r,'score'))}</strong><span>平均综合得分</span></div><div><strong>${fmt(avg(r,'coord'))}</strong><span>平均协调度</span></div></div>${indicator('平均太阳辐射指数',avg(r,'radiation'))}${indicator('平均碳汇覆盖占比',avg(r,'land6'),true)}${indicator('最高优先级县域占比',r.length?r.filter(c=>val(c,'priority')===5).length/r.length:0,true)}<p class="detailNote">省级指标为县域汇总。县域内的系统协调度与地区之间的相似近邻关系分别计算。</p>${p?`<button class="reset" id="enterSelectedProvince">探索${esc(p.name)}县域</button>`:''}`;}
 if(mode==='province'&&isTotal(metric)){
 const region=selectedProv||provinces.find(p=>p.id===pid),list=region?provRows(region):counties,v=list.map(c=>c[metric]).filter(valid);
 html+='<div class="selectedMetric"><span>已覆盖县域小计 · '+totalCoverage(list,metric)+'</span><strong>'+display(v.length?v.reduce((sum,x)=>sum+x,0):null)+'</strong></div><p class="detailNote">仅相加有效县域；'+(metric==='carbonTotal'?'碳排放为 2023 年，部分 2022 年记录':'用电为 2020 年记录')+'。覆盖不完整时不能视为全省总量。</p>';
 }
 $('detail').innerHTML=html;if($('enterSelectedProvince'))$('enterSelectedProvince').onclick=()=>enterProvince((selectedProv||provinces.find(p=>p.id===pid)).id);
 const nextRankingKey=[mode,pid,selectedProv?.id||'',metric,version].join('|');if(nextRankingKey===rankingKey){renderRelations();return;}rankingKey=nextRankingKey;
 const rankingScope=selectedProv&&mode==='province'?provRows(selectedProv):areaRows();const ranking=rankingScope.filter(c=>valid(val(c,metric))).sort((a,b)=>val(b,metric)-val(a,metric)).slice(0,5);$('rankingTitle').textContent=defs[metric][0]+' · 数值前五';$('ranking').innerHTML=ranking.map((c,i)=>`<button class="rank" data-id="${c.id}" title="${esc(c.province+' '+c.name)}"><em>0${i+1}</em><span>${esc(c.name)}</span><b>${display(val(c,metric))}</b></button>`).join('')||'<p class="empty">当前范围暂无有效值。</p>';
 $('ranking').querySelectorAll('button').forEach(b=>b.onclick=()=>{const c=counties.find(c=>c.id===b.dataset.id);pid=c.pid;$('province').value=pid;mode='county';selectCounty(c);fit();});renderRelations();}
function renderRelations(){const c=relationFocus(),rr=c?.relations[version]||[],pool=mode==='county'?counties:provinces;
 const relationHTML=rr.map(r=>{const n=pool.find(x=>x.id===r.id),spatial=Math.exp(-r.distance/(mode==='county'?300:800));return `<button class="relationCard" data-id="${r.id}"><span class="relationName">${esc(n?.name||r.id)}<small>${r.distance.toFixed(1)} km ↗</small></span><span class="relationValues"><span>指标相似<b>${r.similarity.toFixed(3)}</b></span><span>空间接近<b>${spatial.toFixed(3)}</b></span><span>综合关联<b>${r.strength.toFixed(3)}</b></span></span></button>`;}).join('')||'<p class="empty">当前地区指标不完整，暂无可计算关系。</p>';
 $('relationTitle').textContent=c?c.name+' · 近邻':'相似与近邻关系';$('relationList').innerHTML=relationHTML;
 let inline=$('inlineRelations');if(!inline){inline=document.createElement('section');inline.id='inlineRelations';$('detail').after(inline);}
 inline.innerHTML=`<div class="inlineRelationsHead"><h3>${selected||selectedProv?'所选地区':'示例地区'} · 近邻关系</h3><span>${esc(c?.name||'暂无选择')}</span></div>${relationHTML}<p class="detailNote">候选近邻中关联最高的 ${rr.length} 个；综合 = 0.65×相似 + 0.35×空间接近。近邻不等同于共享行政边界。</p>`;
 for(const container of [inline,$('relationList')])container.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(mode==='county'){const n=counties.find(c=>c.id===b.dataset.id);pid=n.pid;$('province').value=pid;selectCounty(n);}else{selectedProv=provinces.find(p=>p.id===b.dataset.id);selected=null;render();fitSelection();}});
 if(c&&rr.length){const overview=document.createElement('button');overview.className='textButton relationOverview';overview.textContent='地图显示全部近邻 ↗';overview.onclick=()=>{const points=[c,...rr.map(r=>pool.find(n=>n.id===r.id)).filter(Boolean)].map(n=>n.center);const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),x=Math.min(...xs),y=Math.min(...ys),w=Math.max(...xs)-x,h=Math.max(...ys)-y,pad=Math.max(w,h,5)*.25;view=[x-pad,y-pad,Math.max(w,1)+2*pad,Math.max(h,1)+2*pad];$('showLinks').checked=true;renderOverlays();setView();};inline.append(overview);}
}
function renderStats(){const key=[pid,version].join('|');if(key===statsKey){syncSelection();return;}statsKey=key;const a=rows();$('total').textContent=a.length.toLocaleString();$('high').textContent=a.filter(c=>val(c,'priority')===5).length.toLocaleString();$('mean').textContent=fmt(avg(a,'coord'));const cnt=[1,2,3,4,5].map(n=>a.filter(c=>val(c,'priority')===n).length);$('distributionCount').textContent=`${a.length.toLocaleString()} 个县域`;$('distribution').innerHTML=cnt.map((n,i)=>`<div class="distLine"><i style="background:${colors[i]}"></i><span>${i+1} 级</span><b>${n}</b><small>${a.length?(n/a.length*100).toFixed(1):'0.0'}%</small></div>`).join('');let offset=0,circ=2*Math.PI*62;$('donut').replaceChildren();for(let i=0;i<5;i++){let len=a.length?cnt[i]/a.length*circ:0;$('donut').append(svg('circle',{cx:90,cy:90,r:62,fill:'none',stroke:colors[i],'stroke-width':17,'stroke-dasharray':`${Math.max(0,len-2)} ${circ-Math.max(0,len-2)}`,'stroke-dashoffset':-offset,transform:'rotate(-90 90 90)'}));offset+=len;}$('donut').append(svg('text',{x:90,y:88,'text-anchor':'middle',fill:'#eaf1f7','font-size':24},a.length.toLocaleString()));$('donut').append(svg('text',{x:90,y:110,'text-anchor':'middle',fill:'#99aabd','font-size':12},'有效县域'));
 const s=$('scatter');s.replaceChildren();for(const y of [0,.2,.4,.6]){s.append(svg('path',{d:`M40 ${185-y/.6*165}H548`,stroke:'#2a3c4d'}));s.append(svg('text',{x:5,y:189-y/.6*165,fill:'#96aabd','font-size':13},y.toFixed(1)));}for(const x of [0,.2,.4,.6,.8,1])s.append(svg('text',{x:35+x*510,y:211,fill:'#96aabd','font-size':13},x.toFixed(1)));
 for(const c of a.filter(c=>valid(val(c,'coord')))){const dot=svg('circle',{cx:40+val(c,'coord')*508,cy:185-val(c,'score')/.6*165,r:selected?.id===c.id?4:2.3,fill:colors[val(c,'priority')-1],opacity:selected?.id===c.id?1:.58});dot.dataset.id=c.id;if(selected?.id===c.id)dot.classList.add('activeDot');dot.append(svg('title',{},`${c.name} · D ${fmt(val(c,'coord'))} · 得分 ${fmt(val(c,'score'))}`));dot.onclick=()=>selectCounty(c);s.append(dot);}}
function render(){const started=performance.now();renderMap();renderDetail();renderStats();document.body.dataset.renderMs=(performance.now()-started).toFixed(1);renderReadingNote();$('coverage').textContent=`${audit.matched} 个结果县域 · ${versionName()} · 非实时数据`;}
function selectCounty(c){ensureCountyDetail(c.pid);selected=c;selectedProv=null;mode='county';if(pid&&pid!==c.pid){pid=c.pid;$('province').value=pid;}render();fitSelection();}
function enterProvince(id){ensureCountyDetail(id);pid=id;$('province').value=pid;mode='county';selected=null;selectedProv=null;render();fit();}
function setView(){$('map').setAttribute('viewBox',view.join(' '));sizeRelationMarks();}
function fitBounds(b){
 const r=$('map').getBoundingClientRect(),aspect=r.width/Math.max(r.height,1);
 const width=Math.max(b.width,.000001),height=Math.max(b.height,.000001);
 const h=Math.max(height,width/aspect)/.76,w=h*aspect;
 view=[b.x+b.width/2-w/2,b.y+b.height/2-h/2,w,h];setView();
}
function sizeRelationMarks(){
 const r=$('map').getBoundingClientRect(),unit=Math.max(view[2]/Math.max(r.width,1),view[3]/Math.max(r.height,1));
 for(const dot of $('linksLayer').querySelectorAll('circle')){
  const region=$('regions').querySelector('[data-id="'+dot.dataset.region+'"]');
  const b=region?.getBBox(),local=b?Math.min(b.width,b.height)*.12:2.4*unit;
  const radius=Math.min(2.4*unit,local);dot.setAttribute('r',radius);dot.style.strokeWidth=Math.min(.5*unit,radius*.2)+'px';
 }
 for(const label of $('labelsLayer').children){label.style.fontSize=(12*unit)+'px';label.style.strokeWidth=(2*unit)+'px';label.setAttribute('dx',6*unit);label.setAttribute('dy',-8*unit);}
}
function restoreNational(){pid='';selected=null;selectedProv=null;$('province').value='';$('search').value='';$('searchStatus').textContent='选择县域可查看详情与近邻关系。';view=[-12,-5,900,850];render();setView();$('tooltip').style.display='none';}

function fitSelection(){const focus=mode==='county'?selected:selectedProv;if(!focus)return;const node=$('regions').querySelector(`[data-id="${focus.id}"]`);if(!node)return;const b=node.getBBox();fitBounds(b);$('tooltip').style.display='none';}
function fit(){if(mode==='county'?selected:selectedProv){fitSelection();return;}if(!pid)view=[-12,-5,900,850];else{const p=provinces.find(p=>p.id===pid),temp=svg('path',{d:p.path});$('map').append(temp);const b=temp.getBBox();temp.remove();fitBounds(b);}setView();}
function zoom(f){const [x,y,w,h]=view,nw=Math.min(1800,Math.max(8,w*f)),nh=h*nw/w;view=[x+(w-nw)/2,y+(h-nh)/2,nw,nh];setView();}
$('metrics').querySelectorAll('button').forEach(b=>b.onclick=()=>{metric=b.dataset.metric;$('metrics').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render();});
$('province').onchange=e=>{pid=e.target.value;selected=null;selectedProv=null;render();fit();};$('version').onchange=e=>{version=e.target.value;render();};$('countyMode').onclick=()=>{mode='county';selectedProv=null;render();};$('provinceMode').onclick=()=>{mode='province';selected=null;render();};
$('reset').onclick=()=>{pid='';selected=null;selectedProv=null;mode='county';$('province').value='';$('search').value='';$('searchStatus').textContent='选择县域可查看详情与近邻关系。';render();fit();};$('fit').onclick=fit;$('zoomIn').onclick=()=>zoom(.75);$('zoomOut').onclick=()=>zoom(1.3333);$('showLinks').onchange=renderOverlays;$('showReserves').onchange=renderOverlays;
$('atlasNav').onclick=()=>{mode='county';selectedProv=null;render();$('atlas').scrollIntoView({behavior:'smooth'});};$('networkNav').onclick=()=>{mode='province';pid='';selected=null;selectedProv=null;$('province').value='';$('showLinks').checked=true;render();fit();$('atlas').scrollIntoView({behavior:'smooth'});};$('modelJump').onclick=()=>$('modelSection').scrollIntoView({behavior:'smooth'});
$('searchForm').onsubmit=e=>{e.preventDefault();const q=$('search').value.trim();if(!q)return;let found=counties.filter(c=>c.id===q||c.name+' '+c.id===q);if(!found.length)found=counties.filter(c=>c.name.includes(q)&&(!pid||c.pid===pid));if(found.length===1){const c=found[0];pid=c.pid;$('province').value=pid;selectCounty(c);fit();$('searchStatus').textContent=`已定位 ${c.province} ${c.name}`;}else $('searchStatus').textContent=found.length?'有多个同名结果，请选择候选项中的县代码。':'未找到匹配县域，请使用完整县名或六位代码。';};
$('map').addEventListener('click',e=>{if(e.target===$('map')&&!dragMoved)restoreNational();});
window.addEventListener('resize',sizeRelationMarks);
$('map').addEventListener('pointerdown',e=>{drag={x:e.clientX,y:e.clientY,v:[...view]};dragMoved=false;});window.addEventListener('pointermove',e=>{if(!drag)return;const r=$('map').getBoundingClientRect(),scale=Math.max(drag.v[2]/r.width,drag.v[3]/r.height),dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5){dragMoved=true;view=[drag.v[0]-dx*scale,drag.v[1]-dy*scale,drag.v[2],drag.v[3]];setView();$('tooltip').style.display='none';}});window.addEventListener('pointerup',()=>{drag=null;setTimeout(()=>dragMoved=false,0);});window.addEventListener('pointercancel',()=>drag=null);$('map').addEventListener('wheel',e=>{e.preventDefault();zoom(e.deltaY>0?1.12:.89);},{passive:false});
function renderModel(){const best=model.results.find(r=>r.id===model.selected),baseline=model.results.find(r=>r.id==='poly_baseline');$('chosenModel').textContent='已采用 · '+model.selected_name;$('modelStats').innerHTML=`<div><span>独立留出 R²</span><strong>${best.test.r2_log.toFixed(3)}</strong><small>基线 ${baseline.test.r2_log.toFixed(3)}</small></div><div><span>GDP 平均绝对误差</span><strong>${best.test.mae_gdp.toFixed(1)}<em>亿元</em></strong><small>基线 ${baseline.test.mae_gdp.toFixed(1)} 亿元</small></div><div><span>独立验证县域</span><strong>${model.test_samples}</strong><small>${model.test_cities} 个地级市组</small></div>`;
 $('modelTable').innerHTML=model.results.map(r=>`<tr class="${r.id===model.selected?'chosen':''}"><td>${r.name}${r.id===model.selected?' ✓':''}</td><td>${r.cv.r2_log.toFixed(3)}</td><td>${r.test.r2_log.toFixed(3)}</td><td>${r.test.mae_gdp.toFixed(1)}</td></tr>`).join('');$('modelSample').textContent=`${model.training_samples} 条有效训练样本，${model.selection_samples} 条用于分组五折选模，${model.test_samples} 条独立留出。未因残差大而删去样本。模型选择先于留出评估。`;
 let plot=$('modelPlot'),max=Math.ceil(Math.log10(Math.max(...model.test_points.flatMap(p=>[p.observed,p.predicted]))+1)),scale=v=>Math.log10(v+1)/max;plot.replaceChildren();for(let i=0;i<=max;i++){let x=50+i/max*350,y=225-i/max*195;plot.append(svg('path',{d:`M50 ${y}H400 M${x} 30V225`,stroke:'#263b4c'}));let label=i===0?'0':i===1?'10':`10${['','','²','³','⁴','⁵'][i]||'^'+i}`;plot.append(svg('text',{x:x-9,y:247,fill:'#99aabd','font-size':12},label));plot.append(svg('text',{x:10,y:y+4,fill:'#99aabd','font-size':12},label));}plot.append(svg('path',{d:'M50 225L400 30',stroke:'#ffbb60','stroke-dasharray':'5 5',opacity:.6}));for(const p of model.test_points){const c=svg('circle',{cx:50+scale(p.observed)*350,cy:225-scale(p.predicted)*195,r:2.4,fill:'#72a79e',opacity:.7});c.append(svg('title',{},`${p.id} 观测 ${p.observed.toFixed(1)} / 预测 ${p.predicted.toFixed(1)} 亿元`));plot.append(c);}plot.append(svg('text',{x:310,y:264,fill:'#99aabd','font-size':12},'观测 GDP / 亿元'));plot.append(svg('text',{x:50,y:17,fill:'#99aabd','font-size':12},'预测 GDP / 亿元'));}
$('aboutBody').innerHTML=`<p>图谱保留原研究数据，并新增可复现的 GDP 估计、系统协调重算、地区关联和保护区叠加。</p><h3>数据覆盖与 GDP 方案</h3><p>边界共 ${audit.boundary_count} 条，匹配研究结果 ${audit.matched} 条。已有正值统计 GDP 直接采用；214 个缺失与15个零值使用灯光模型估计。按该方案计算协调度与研究优先级。</p><h3>总量地图与研究排名</h3><p>碳排放总量直接采用 final_result.csv 的 CO2排放量_吨，2,826 个县域有正值记录（2,737 个为2023年、89个为2022年）。用电总量因覆盖不足已从地图与对照中移除。源表缺失占位0不视为真实零值。总量仅用于地图与双县对照；协调度光伏系统的土地项已改为1减不可用占比；优先级及相似关系采用六指标修订模型，不使用总量替换减排需求强度。省级总量为已覆盖县域小计，缺失县不估算。</p><h3>县域内的耦合协调</h3><p>资源系统 A = 0.4×太阳辐射 + 0.3×坡度指标 + 0.2×(1−不可用土地占比) + 0.1×GDP指数；低碳相关系统 B = 0.5×原碳排放强度指数 + 0.3×碳汇占比 + 0.2×原用电强度指数。沿用原研究权重与指标方向，不代表这些假设已重新论证。</p><p>C = 2√(A×B)/(A+B)；T = 0.6A+0.4B；D = √(C×T)。本轮复核了该计算并保持其数值，协调标签仍按五类聚类中心排序。D 单独展示，不再作为优先级的输入。保护区不再次扣减潜力。</p><h3>修订后的开发优先级</h3><p>使用减排需求强度、碳汇覆盖占比、不可用土地占比、坡度适宜指标、经济基础指数、自然光伏潜力指数六项指标。按全国有效样本最小值和最大值归一化，各占1/6权重，以欧氏距离计算到理想点与负理想点的距离；得分=到负理想点距离/两种距离之和。这里高碳强度表示更大的减排需求，不表示更好的低碳表现。等权是公开的基准设定，不是经外部结果学习得到的最优权重。</p><p>为避免基础指标重复计入，派生协调度不再进入排名。全国综合得分的最小值与最大值之间均分为五个区间，1级最低、5级最高；不再强制每组20%。分组是研究展示标准，不是行政认定或工程适建结论。固定标尺下，正向输入增加时得分不会下降。</p><h3>地区之间的关系连线</h3><p>${esc(model.network)}</p><p>六项指标与修订排名一致：减排需求强度、碳汇覆盖占比、不可用土地占比、坡度适宜指标、经济基础指数、自然光伏潜力指数。地区指标须完整才计算关系。省级网络使用县域指标均值，并沿用县域评分的归一化标尺。权重与带宽为本图谱的透明展示设定，不是经验证的因果参数。县域无选择时，以当前范围得分最高县域为关联示例。</p><h3>原始 GDP 完整性与默认版本</h3><p>2,891个边界县域中，2,662个有正值统计GDP，214个缺失、15个为0。默认使用原统计GDP，仅对这229个缺失或零值县域采用灯光模型估计，并重新归一化。填补表额外147个正值来源未验证，未当作实测值。已有统计值不由预测值替换。</p><p>即使全部统计GDP齐全，夜间灯光仍可作为经济活动强度的独立指标、异常核查线索，以及具备栅格时的县内空间分布信息。两年亮度变化还需核实传感器与辐射校准一致，不能直接解释为GDP增长。</p><h3>GDP 模型与验证</h3><p>${esc(model.split)}。样条、树模型使用灯光两年值、均值与对数变化、县域面积及经纬度；多项式基线使用灯光均值及平方、对数变化。因此提升来自模型与新增特征的共同作用，不能全部归因于算法。</p><p>训练目标为 log(1+GDP)。R² 均在此尺度比较；MAE 在亿元尺度计算。网站显示全样本重新拟合后的估计，独立验证指标来自重拟合前的留出预测。预测可能存在外推误差，不能据此宣称统计 GDP 有误。未用碳排放/GDP、用电/GDP 等目标派生量预测 GDP。</p><p>${esc(model.gdp_unit_check)}</p><h3>保护区与面积</h3><p>保护区.shp 共 ${model.reserve_count} 个要素；${model.reserve_counties} 个县域相交。几何转到 EPSG:6933 等积投影后做相交、合并去重并计算面积。0 表示未与本次所给要素相交，不证明该县没有其他保护地；数据时效和完整性待确认。县域与保护区均按源文件 WGS84 读取，网页几何仅作显示简化。</p><h3>指标含义与年份</h3><p>${esc(model.land_caveat.replaceAll('land3','不可用土地占比').replaceAll('slope','坡度指标'))} 单位GDP碳排放与用电均为源表归一化指数，不是实际吨/亿元或kWh/亿元。平均太阳辐射反映光照条件；自然光伏潜力综合自然条件与可开发规模，两者不是同一指标。土地、经济等部分数据为2023，整体是多年份研究快照。</p><p>原优先级以5级最高，依据最终表与代码；原文一处相反表述未采用。省级地图除保护区面积比与5级占比外均为有效县域均值，不冒充独立的省级耦合模型。</p><h3>来源</h3><p>counties.shp/dbf、保护区.shp、光伏优先级结果_最终版.csv、Finally.csv、county_solar_norm.csv、cleaned_lightgdp.csv、final_result.csv 与原论文。保留输入文件，新增分析文件供复核。县均值无法恢复缺失的像元或支持地块级选址。</p><details><summary>未匹配结果县代码</summary><p>${audit.unmapped_result_ids.join('、')}</p></details><p><a href="https://scikit-learn.org/stable/modules/cross_validation.html" target="_blank" rel="noopener">分组交叉验证方法文档</a></p>`;
for(const id of ['aboutBtn','footerAbout','networkExplain'])$(id).onclick=()=>$('about').showModal();$('closeAbout').onclick=()=>$('about').close();$('about').onclick=e=>{if(e.target===$('about')){const r=$('about').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('about').close();}};
const storyContent=[
 ['为什么要回到县域？','同样的阳光，并不意味着同样的开发条件。资源禀赋、经济活动与生态边界在不同地区交错，单一指标难以呈现这种差异。',[['01','看见资源差异','从太阳辐射、坡度与土地指标认识空间条件。'],['02','连接发展需求','用统计 GDP 与经济活动线索观察区域差异。'],['03','识别生态边界','将碳汇覆盖与所给保护区放到同一张地图。']]],
 ['从一张排名表，走向可解释的比较。','本研究希望帮助使用者理解“为什么这里优先”，并比较不同县域的发展条件。',[['01','空间可读','用省县地图展示差异，定位具体地区。'],['02','依据可查','同时展示指标值、统计来源与缺失补估。'],['03','地区可比','在共同刻度下比较县域指标和条件。']]],
 ['先理解条件，再讨论优先级。','将宏观目标逐步转译为研究指标与区域比较。当前数据支持县域尺度探索，不足以完成地块级工程选址。',[['01','资源评估 →','查看辐射、坡度与土地条件。'],['02','协调比较 →','联合观察经济与碳汇相关指标、模型协调度。'],['03','约束复核 →','核查保护地、土地口径；另需电网容量与现场资料。']]]
];
function showStory(index){const [title,description,steps]=storyContent[index];document.querySelectorAll('[data-story]').forEach((b,i)=>{b.setAttribute('aria-selected',String(i===index));b.tabIndex=i===index?0:-1;});$('storyPanel').setAttribute('aria-labelledby','storyTab'+index);$('storyPanel').innerHTML=`<h3>${title}</h3><p>${description}</p><div class="storySteps">${steps.map(([n,t,d])=>`<div><em>${n}</em><span><b>${t}</b><small>${d}</small></span></div>`).join('')}</div>`;}
document.querySelectorAll('[data-story]').forEach((b,i)=>{b.onclick=()=>showStory(i);b.onkeydown=e=>{let next;if(e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;if(next!==undefined){e.preventDefault();showStory(next);$('storyTab'+next).focus();}};});
showStory(0);render();fit();
 const modelObserver=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){renderModel();modelObserver.disconnect();}},{rootMargin:'250px'});modelObserver.observe($('modelSection'));
const evidenceStyle=document.createElement('link');evidenceStyle.rel='stylesheet';evidenceStyle.href='competition.css?v=16';document.head.append(evidenceStyle);
const evidenceScript=document.createElement('script');evidenceScript.src='competition.js?v=16';evidenceScript.onload=()=>{const journey=document.createElement('script');journey.src='journey.js?v=16';document.body.append(journey);};document.body.append(evidenceScript);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'explore_solar_county',title:'定位光伏县域',description:'按六位县代码定位县域，显示当前版本指标和相似近邻关系。',inputSchema:{type:'object',properties:{county_id:{type:'string',pattern:'^[0-9]{6}$'}},required:['county_id'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input.county_id!=='string'||!/^\d{6}$/.test(input.county_id))throw new Error('请输入六位县代码');const c=counties.find(c=>c.id===input.county_id);if(!c)throw new Error('该县代码未匹配到地图边界');pid=c.pid;$('province').value=pid;selectCounty(c);fit();return {county_id:c.id,name:c.name,version,score:val(c,'score'),coordination:val(c,'coord'),priority:val(c,'priority'),relations:c.relations[version]};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

// Detailed geometry is fetched only when the user requests its area.
const detailJobs=new Map();let reserveJob=null;
async function ensureCountyDetail(id){
 if(!ATLAS_ASSETS.detail[id])return;
 if(!detailJobs.has(id))detailJobs.set(id,loadAtlasAsset(ATLAS_ASSETS.detail[id]).then(paths=>{
  for(const c of provinceRows.get(id)||[]){if(paths[c.id]){c.path=paths[c.id];if(mode==='county')$('regions').querySelector('[data-id="'+c.id+'"]')?.setAttribute('d',c.path);}}
  sizeRelationMarks();return true;
 }).catch(()=>{detailJobs.delete(id);$('geometryStatus').textContent='当前显示概览边界；再次选择可重试精细县界。';return false;}));
 return detailJobs.get(id);
}
async function ensureReserves(){
 if(reserveJob)return reserveJob;
 $('geometryStatus').textContent='正在载入保护区实际边界…';
 reserveJob=loadAtlasAsset(ATLAS_ASSETS.reserves).then(data=>{reserves.push(...data);$('geometryStatus').textContent='保护区边界已载入';renderOverlays();}).catch(()=>{reserveJob=null;$('geometryStatus').innerHTML='保护区边界暂未载入。<button id="retryReserves">重试</button>';$('retryReserves').onclick=ensureReserves;});return reserveJob;
}
document.querySelectorAll('[data-protected-view]').forEach(b=>b.onclick=()=>{protectedView=b.dataset.protectedView;if(protectedView==='coverage')$('showReserves').checked=false;render();});

function renderReadingNote(){
 const list=areaRows(),n=list.filter(c=>valid(val(c,metric))).length;
 const total=isTotal(metric),scope=selectedProv?.name||provinces.find(p=>p.id===pid)?.name||'全国';
 $('mapReading').innerHTML='<span><small>当前读图</small><b>'+esc(defs[metric][0])+'</b></span><span><small>有效县域</small><b>'+n.toLocaleString()+' / '+list.length.toLocaleString()+'</b></span><p>'+(metric==='protected'?(protectedView==='footprint'?'看实际保护地的位置；点击县域查看相交面积与覆盖率。':'看县域内保护区占比；颜色不是保护区的实际范围。'):total?'比较地区活动规模。缺失区域以斜线显示；省级为已覆盖县域小计，不能当作完整省级总量。':'点击地区居中放大，点击空白返回全国；滚轮缩放，拖动平移。')+'</p>';
}
