'use strict';
// Every statement and comparison below is computed from the shipped snapshot.
const comparable=counties.filter(c=>valid(c.priority)&&valid(c.v3.priority));
const highSet=counties.filter(c=>c.v3.priority===5);
const overlapHigh=highSet.filter(c=>c.protected>0);
const resourceRank=counties.filter(c=>valid(c.radiation)&&valid(c.v3.priority)).sort((a,b)=>b.radiation-a.radiation||a.id.localeCompare(b.id));
const resourceLeaders=resourceRank.slice(0,Math.ceil(resourceRank.length*.2));
const resourceAlsoHigh=resourceLeaders.filter(c=>c.v3.priority===5);
const storyZone=document.createElement('section');storyZone.className='evidenceSection panel';storyZone.id='evidenceSection';
storyZone.innerHTML=`<div class="sectionHeading"><div><div class="eyebrow">EVIDENCE / 让结论经得起比较</div><h2>最亮的地方，就是最好的选择吗？</h2><p>从资源看见机会，从对照看见差异，从数据来源理解结论。</p></div><a class="evidenceAnchor" href="#compareSection">开始双县对照 ↓</a></div>
<div class="findingGrid"><button class="findingCard" id="findingResource"><span>01 / 资源视角</span><strong>${resourceAlsoHigh.length}<small> / ${resourceLeaders.length} 县域</small></strong><p>辐射指数前 20% 的县域中，进入研究优先级 5 级的数量。资源排序与综合排序并不相同；这不是实际发电效果。</p><em>探索资源地图 ↗</em></button><button class="findingCard" id="findingEcology"><span>02 / 生态视角</span><strong>${overlapHigh.length}<small> / ${highSet.length} 县域</small></strong><p>统计优先版 5 级县域中，与所给保护区有空间相交的县域数量。县内相交不等于整个县域禁止开发。</p><em>查看保护区图层 ↗</em></button><button class="findingCard" id="findingCoverage"><span>03 / 数据视角</span><strong>92.1<small>% 统计 GDP 覆盖</small></strong><p>2,891 个边界县域中，2,662 个使用已有正值统计 GDP。其余 229 个采用灯光模型补缺。</p><em>查看数据来源 ↓</em></button></div>
<div id="compareSection" class="compareSection"><div class="sectionHeading"><div><div class="eyebrow">COUNTY / SIDE BY SIDE</div><h3>两个县域，两种条件。</h3><p>共同刻度下比较指标；高数值不一定代表更适宜开发。</p></div><button id="useSelectedCounty">将地图所选县加入 A</button></div><div class="compareControls"><label>A · 琥珀<select id="compareA" aria-label="对照县域A"></select></label><label>B · 青绿<select id="compareB" aria-label="对照县域B"></select></label><button id="swapCompare">交换 A / B</button></div><div id="comparisonSummary" aria-live="polite"></div><div id="comparisonBars"></div><p class="evidenceNote" id="comparisonSource"></p><button id="downloadCompare" class="textButton">下载这组对照数据 CSV ↓</button><p id="compareStatus" role="status" class="evidenceNote"></p></div>`;
$('contextSection').before(storyZone);
const comparisonMetrics=['radiation','solar','slope','land3','gdp','carbonTotal','land6','protected','coord','score'];
const orderedCounties=[...counties].sort((a,b)=>a.id.localeCompare(b.id));
const options=orderedCounties.map(c=>`<option value="${c.id}">${esc(c.province)} · ${esc(c.name)} / ${c.id}</option>`).join('');
$('compareA').innerHTML=options;$('compareB').innerHTML=options;
const defaultA=counties.find(c=>c.id==='632221')||orderedCounties[0];
const defaultB=counties.find(c=>c.id===(defaultA.relations.hybrid||[])[0]?.id)||orderedCounties[1];
$('compareA').value=defaultA.id;$('compareB').value=defaultB.id;
const compareMax=Object.fromEntries(comparisonMetrics.map(k=>[k,isTotal(k)?Math.max(...counties.map(c=>c[k]).filter(valid)):1]));
function renderComparison(){const a=counties.find(c=>c.id===$('compareA').value),b=counties.find(c=>c.id===$('compareB').value);
 $('comparisonSummary').innerHTML=`<div><small>当前比较 · ${versionName()}</small><strong><span>${esc(a.name)}</span><i>×</i><span>${esc(b.name)}</span></strong></div><div class="compareGrades"><span>A · ${display(val(a,'priority'),'priority')}</span><span>B · ${display(val(b,'priority'),'priority')}</span></div>`;
 $('comparisonBars').innerHTML=comparisonMetrics.map(k=>{const av=val(a,k),bv=val(b,k);return `<div class="compareMetric"><div><b>${defs[k][0]}</b><small>${defs[k][1]}</small></div><div class="doubleTrack"><div><i style="width:${valid(av)?Math.max(0,Math.min(1,av/compareMax[k]))*100:0}%"></i><span>A ${display(av,k)}</span></div><div><i style="width:${valid(bv)?Math.max(0,Math.min(1,bv/compareMax[k]))*100:0}%"></i><span>B ${display(bv,k)}</span></div></div><span class="metricDelta">${valid(av)&&valid(bv)?`A − B<br>${(av-bv)>0?'+':''}${isTotal(k)?display(av-bv,k):(av-bv).toFixed(3)}`:'不可比较'}</span></div>`;}).join('');
 renderRankingExplanation(a,b);$('comparisonSource').textContent=`GDP 来源（统计优先口径）：A ${a.gdpHybridSource||'未记录'}；B ${b.gdpHybridSource||'未记录'}。总量条形以全国有效县域最大值为共同上限，其他指标使用 0–1 刻度。碳排放 A ${a.carbonTotalYear||'缺失'} / B ${b.carbonTotalYear||'缺失'} 年。碳排放总量用于地图和对照；研究排名与关联使用六指标等权修订模型。`;
}
for(const id of ['compareA','compareB'])$(id).onchange=renderComparison;
$('version').addEventListener('change',renderComparison);
$('swapCompare').onclick=()=>{const a=$('compareA').value;$('compareA').value=$('compareB').value;$('compareB').value=a;renderComparison();};
$('useSelectedCounty').onclick=()=>{if(!selected){$('compareStatus').textContent='请先在地图、搜索或县域列表中选择一个县域。';return;}$('compareA').value=selected.id;renderComparison();$('compareStatus').textContent=`已将 ${selected.name} 加入 A。`;};
function exploreMetric(k,reserve=false){metric=k;mode='county';pid='';selected=null;selectedProv=null;$('province').value='';$('showReserves').checked=reserve;document.querySelectorAll('#metrics button').forEach(b=>b.classList.toggle('active',b.dataset.metric===k));render();fit();$('atlas').scrollIntoView({behavior:'smooth'});}
$('findingResource').onclick=()=>exploreMetric('radiation');$('findingEcology').onclick=()=>exploreMetric('protected',true);$('findingCoverage').onclick=()=>$('passport').scrollIntoView({behavior:'smooth'});
$('downloadCompare').onclick=()=>{const a=counties.find(c=>c.id===$('compareA').value),b=counties.find(c=>c.id===$('compareB').value),quote=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const lines=[['版本','县代码','县名','指标','值','口径'],...[a,b].flatMap(c=>comparisonMetrics.map(k=>[versionName(),c.id,c.name,defs[k][0],val(c,k),defs[k][1]]))];const blob=new Blob(['\uFEFF'+lines.map(r=>r.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`逐光-县域对照-${a.id}-${b.id}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('compareStatus').textContent='对照数据已生成，包含当前版本和指标口径。';};
renderComparison();
const evidenceNav=document.createElement('a');evidenceNav.href='#evidenceSection';evidenceNav.textContent='发现与对照';document.querySelector('header nav').append(evidenceNav);
const passport=document.createElement('section');passport.className='passport panel';passport.id='passport';
passport.innerHTML=`<div class="sectionHeading"><div><div class="eyebrow">DATA PASSPORT / 每个结论都有来处</div><h2>数据不是黑箱。</h2><p>区分统计记录、模型估计、空间计算与研究假设。</p></div><button id="passportMethods" class="textButton">完整计算方法 ↗</button></div><div class="passportGrid"><div><span class="passportMark">统计记录</span><strong>2,662<small> 个县域</small></strong><p>已有正值 GDP 保留原值；地图口径共 2,891 个县域。统计记录仍需以源年鉴与边界年份核对。</p></div><div><span class="passportMark">模型补缺</span><strong>229<small> 个县域</small></strong><p>214 个缺失与 15 个零值采用灯光模型估计；预测不能当作统计实测。模型效果见独立留出验证。</p></div><div><span class="passportMark">空间计算</span><strong>1,028<small> 个要素</small></strong><p>所给保护区与县域相交、等积投影计面积并合并去重。未相交不能证明不存在保护地。</p></div><div><span class="passportMark">研究假设</span><strong>多年份<small> 快照</small></strong><p>辐射为 2016 年，部分经济土地数据为 2023 年；不可用土地占比越大，土地约束越强；评分按负向处理。</p></div></div><div class="evidencePipeline" aria-label="数据处理流程"><span>源表与边界<br><small>县代码匹配</small></span><b>→</b><span>GDP 补缺<br><small>地级市分组验证</small></span><b>→</b><span>协调与分级<br><small>六指标修订评分</small></span><b>→</b><span>地图与对照<br><small>口径随图呈现</small></span></div><p class="evidenceNote">数据源为研究团队提供的论文、县域表格和矢量文件。碳排放与用电指标方向、保护区版本、边界适配和源数据授权仍应在正式参赛材料中核实；本图谱不声称测得实际减排量或输电关系。</p>`;
$('modelSection').after(passport);$('passportMethods').onclick=()=>$('about').showModal();
// A short, user-controlled presentation path retains the full working map.
const guide=document.createElement('div');guide.className='guidedEntry';guide.innerHTML='<span>第一次来到逐光？</span><button id="startGuide">四步读懂这张地图 <b>↗</b></button><small>资源 → 生态 → 对照 → 依据</small>';document.querySelector('.intro').after(guide);
const guidePanel=document.createElement('aside');guidePanel.className='guidePanel';guidePanel.hidden=true;guidePanel.setAttribute('aria-label','作品导览');guidePanel.innerHTML='<div><span id="guideStep"></span><button id="closeGuide" aria-label="关闭导览">×</button></div><h3 id="guideTitle"></h3><p id="guideText"></p><div><button id="guidePrev">上一步</button><button id="guideNext">下一步 →</button></div>';document.body.append(guidePanel);
const guidedSteps=[['看见资源','先看太阳辐射的空间差异。此处为归一化指数，不能直接解读为发电量。',()=>exploreMetric('radiation')],['看见边界','将保护区放在县域背景中。县域内部有保护区，不意味着整县都不能开发。',()=>exploreMetric('protected',true)],['解释差异','使用两县同刻度条形图检查具体条件，不把所有高数值都解释为优势。',()=>$('compareSection').scrollIntoView({behavior:'smooth'})],['追溯依据','已有统计 GDP 直接采用，只对缺失与零值补估。区分统计记录、模型估计和空间计算。',()=>$('passport').scrollIntoView({behavior:'smooth'})]];
let guideIndex=0;
function updateGuide(){const [title,description,action]=guidedSteps[guideIndex];guidePanel.hidden=false;$('guideStep').textContent=`READING THE ATLAS / 0${guideIndex+1}`;$('guideTitle').textContent=title;$('guideText').textContent=description;$('guidePrev').disabled=guideIndex===0;$('guideNext').textContent=guideIndex===3?'完成导览 ✓':'下一步 →';action();}
$('startGuide').onclick=()=>{guideIndex=0;updateGuide();};$('closeGuide').onclick=()=>{guidePanel.hidden=true;};$('guidePrev').onclick=()=>{if(guideIndex>0){guideIndex--;updateGuide();}};$('guideNext').onclick=()=>{if(guideIndex===3){guidePanel.hidden=true;}else{guideIndex++;updateGuide();}};

function renderRankingExplanation(a,b){
 let panel=$('rankingExplanation');if(!panel){panel=document.createElement('details');panel.id='rankingExplanation';panel.className='rankingExplanation';$('comparisonBars').after(panel);}
 const keys=['carbon','land6','land3','slope','gdp','solar'],meta=model.priorityRevision;
 const normalized=(c,k,i)=>{const v=val(c,k);if(!valid(v))return null;const z=(v-meta.low[i])/(meta.high[i]-meta.low[i]);return meta.directions?.[i]===-1?1-z:z;};
 const range=c=>{const g=val(c,'priority');return valid(g)?meta.thresholds[g-1].toFixed(4)+'–'+meta.thresholds[g].toFixed(4):'暂无数据';};
 panel.innerHTML='<summary>为什么两县分组不同？查看六项排名输入</summary><p>得分 '+fmt(val(a,'score'))+' / '+fmt(val(b,'score'))+'；所在组分数区间 A '+range(a)+'，B '+range(b)+'。</p><div class="tableWrap"><table><thead><tr><th>排名指标</th><th>A · '+esc(a.name)+'</th><th>B · '+esc(b.name)+'</th><th>权重</th></tr></thead><tbody>'+keys.map((k,i)=>'<tr><td>'+meta.featureLabels[i]+'</td><td>'+fmt(normalized(a,k,i))+'</td><td>'+fmt(normalized(b,k,i))+'</td><td>1/6</td></tr>').join('')+'</tbody></table></div><p>表中是统一标尺下的评分输入。高碳强度在此表示减排需求较大；不代表环境表现更好。协调度单独展示，不重复进入排名；两县邻近并不要求指标一致。</p>';
}
