'use strict';
(()=>{
 const main=document.querySelector('main'),pages={};
 for(const key of ['atlas','context','findings']){const p=document.createElement('div');p.className='appPage';p.dataset.page=key;main.prepend(p);pages[key]=p;}
 function move(node,page){if(!node)return;const fold=node.closest('.supportingFold');pages[page].append(node);if(fold&&fold!==node)fold.remove();}
 for(const node of [...main.children])if(!node.classList.contains('appPage')&&node.tagName!=='FOOTER')move(node,'atlas');
 move($('contextSection'),'context');move($('evidenceSection'),'findings');move($('passport'),'findings');move(document.querySelector('.caseJourney'),'findings');
 move($('modelSection'),'atlas');
 const nav=document.querySelector('header nav');nav.innerHTML='<button id="atlasNav" data-page-link="atlas">地图与模型</button><button id="networkNav">区域关联</button><button data-page-link="context">背景与政策</button><button data-page-link="findings">发现与对照</button>';
 let page='atlas';
 function showPage(key,scroll=true){page=key in pages?key:'atlas';for(const [k,p] of Object.entries(pages))p.hidden=k!==page;for(const b of nav.querySelectorAll('[data-page-link]')){b.classList.toggle('navActive',b.dataset.pageLink===page);b.setAttribute('aria-current',b.dataset.pageLink===page?'page':'false');}document.body.dataset.page=page;if(scroll)window.scrollTo({top:0,behavior:'instant'});requestAnimationFrame(()=>{layout();if(page==='atlas'){fit();renderOverlays();renderModel();}});}
 for(const b of nav.querySelectorAll('[data-page-link]'))b.onclick=()=>{history.pushState(null,'','#'+b.dataset.pageLink);showPage(b.dataset.pageLink);};
 document.addEventListener('click',e=>{const link=e.target.closest('a[href^="#"]');if(!link)return;const target=$(link.hash.slice(1));if(target){const p=target.closest('.appPage');if(p){e.preventDefault();showPage(p.dataset.page,false);requestAnimationFrame(()=>target.scrollIntoView({behavior:'smooth'}));}}},true);
 for(const id of ['goToCompare','caseCompare'])$(id)?.addEventListener('click',()=>showPage('findings'));
 for(const id of ['locateCompareA','locateCompareB','frameComparison','findingResource','findingEcology'])$(id)?.addEventListener('click',()=>showPage('atlas'));
 const tools=document.querySelector('.stageTools');if(tools){const fold=document.createElement('details');fold.className='exportTools';fold.innerHTML='<summary>演示与下载</summary>';tools.before(fold);fold.append(tools);}
 // Close the gap caused by grid stretch and a tall viewBox with unused space.
 const bottom=document.querySelector('.bottom');bottom.classList.add('mapInsights');document.querySelector('.mapPanel').append(bottom);document.querySelector('.bottom .relation').hidden=true;
 const relations=$('inlineRelations');if(relations)relations.hidden=true;
 const routeDetail=renderDetail;renderDetail=function(){routeDetail();if($('inlineRelations'))$('inlineRelations').hidden=true;updateNetworkCard();let rank=$('selectedRank');if(!rank){rank=document.createElement('p');rank.id='selectedRank';rank.className='detailNote';$('detail').append(rank);}rank.hidden=!selected;if(selected){const g=val(selected,'priority'),t=model.priorityRevision.thresholds;rank.textContent='全国第 '+selected.priorityRank+' / '+model.priorityRevision.samples+' 位 · 本级得分 '+(g===1?'≤ '+t[1].toFixed(6):g===5?'> '+t[4].toFixed(6):'> '+t[g-1].toFixed(6)+' 至 ≤ '+t[g].toFixed(6))+'。接近阈值时请比较连续得分。';}};
 const originalFit=fit;
 fit=function(){if(pid||selected||selectedProv){originalFit();return;}const b={x:0,y:5,width:868,height:575},r=$('map').getBoundingClientRect(),aspect=r.width/Math.max(r.height,1);const h=Math.max(b.height,b.width/aspect)/.92;view=[b.x+b.width/2-h*aspect/2,b.y+b.height/2-h/2,h*aspect,h];setView();};
 const inset=svg('svg',{viewBox:'390 560 350 290',class:'southSeaInset','aria-label':'南海诸岛位置示意，沿用所给边界'});for(const p of provinces)inset.append(svg('path',{d:p.path,fill:'#72a79e',stroke:'#bad0d6','stroke-width':1}));const insetBox=document.createElement('div');insetBox.className='southSeaBox';insetBox.append(inset);const insetLabel=document.createElement('small');insetLabel.textContent='南海诸岛 · 边界示意';insetBox.append(insetLabel);document.querySelector('.mapCanvas').append(insetBox);
 const originalRestore=restoreNational;restoreNational=function(){originalRestore();fit();};
 function layout(){if(page!=='atlas')return;const canvas=document.querySelector('.mapCanvas');canvas.style.height=(innerWidth<900?Math.max(340,Math.min(470,innerHeight-410)):Math.max(430,Math.min(600,innerHeight-380)))+'px';}
 window.addEventListener('resize',()=>requestAnimationFrame(()=>{layout();if(!pid&&!selected&&!selectedProv)fit();}));
 document.querySelector('.intro h1').textContent='县域光伏 · 资源、约束与开发优先级';
 const relationship=document.createElement('section');relationship.id='relationshipPanel';relationship.className='networkCard';relationship.innerHTML='<div class="chartHeading"><h3>地区之间：相似与空间接近</h3><span id="networkLevel"></span></div><div class="networkControls"><label>显示密度<select id="relationDensity"><option value="overview">概览 · 每省1条</option><option value="focus">焦点 · 最近邻4条</option><option value="regional">区域 · 最多40条</option></select></label><label>关联强度至少 <output id="relationThresholdValue">0.00</output><input id="relationThreshold" type="range" min="0" max="1" step="0.05" value="0"></label></div><p id="relationExplanation"></p><div id="networkNumbers"></div><p class="networkImpact"><b>不参与研究排名。</b>连线用于找到可比较的地区；不能据此推断输电、因果或开发收益。</p><details><summary>如何计算？与县域协调度有什么区别？</summary><p>指标相似度 = exp(−2×六指标归一化后的等权欧氏距离)；空间接近度 = exp(−直线距离/带宽)。综合关联 = 0.65×相似度 + 0.35×空间接近度。县域带宽300km，省级800km；参数是研究展示设定。县域从最近8县、省份从最近5省中取关联最高4个，不等于接壤关系。</p><p>耦合协调度描述一个县内资源与低碳相关两系统的联合状态；地图连线描述两个地区的指标相近与距离接近。两者不互相替代。连线阈值只改变显示，不改变县域得分或等级。</p></details>';
 $('detail').after(relationship);
 let density='overview',threshold=0;
 const edgePool=()=>{const chosen=mode==='county'?selected:selectedProv;let pool=[],scopeLabel='';if(density==='focus'||chosen){const c=chosen||relationFocus();scopeLabel=(c?.name||'示例地区')+' · 焦点';for(const r of c?.relations.hybrid||[])pool.push({from:c,to:(mode==='county'?counties:provinces).find(n=>n.id===r.id),...r});}else{const regional=density==='regional'&&pid;const nodes=regional?counties.filter(c=>c.pid===pid):provinces;scopeLabel=regional?'省内县域网络':'全国省域骨架';for(const c of nodes)for(const r of (c.relations.hybrid||[]).slice(0,regional?2:density==='regional'?2:1))pool.push({from:c,to:nodes.find(n=>n.id===r.id),...r});}const seen=new Set();pool=pool.filter(e=>e.to&&e.strength>=threshold&&(()=>{const k=[e.from.id,e.to.id].sort().join('|');if(seen.has(k))return false;seen.add(k);return true;})()).sort((a,b)=>b.strength-a.strength);return {edges:pool.slice(0,density==='regional'?40:30),scopeLabel};};
 const overlaysBefore=renderOverlays;renderOverlays=function(){overlaysBefore();const {edges,scopeLabel}=edgePool();if(!$('showLinks').checked||metric==='protected'){updateNetworkCard();return;}const group=$('linksLayer');group.replaceChildren();for(const e of edges){const [x,y]=e.from.center,[a,b]=e.to.center,dx=a-x,dy=b-y;group.append(svg('path',{d:`M${x},${y}Q${(x+a)/2-dy*.12},${(y+b)/2+dx*.12} ${a},${b}`,class:'relationLine',opacity:.2+.65*e.strength}));for(const c of [e.from,e.to]){const attrs={cx:c.center[0],cy:c.center[1],r:0,'data-region':c.id,class:'relationNode'};const dot=svg('circle',attrs);if(!$( 'regions').querySelector('[data-id="'+c.id+'"]')){const unit=view[2]/Math.max($('map').getBoundingClientRect().width,1);dot.setAttribute('r',1.8*unit);dot.dataset.overview='true';}group.append(dot);}}sizeRelationMarks();$('linkStatus').textContent=scopeLabel+' · '+edges.length+' 条（已去重）';updateNetworkCard();};
 function updateNetworkCard(){if(!$('networkLevel'))return;const {edges,scopeLabel}=edgePool();$('networkLevel').textContent=scopeLabel;$('relationExplanation').textContent=(selected||selectedProv?'选中地区自动切换到焦点近邻；返回全国后恢复概览。':'全国展示省域骨架，避免数千条县域连线遮挡地图。选择省份再切到区域，可看省内县域网络。');$('networkNumbers').innerHTML=edges.slice(0,4).map(e=>'<button data-neighbor="'+e.to.id+'"><span>'+esc(e.from.name)+' → '+esc(e.to.name)+'</span><small>相似 '+e.similarity.toFixed(3)+' · 距离 '+e.distance.toFixed(0)+'km · 关联 '+e.strength.toFixed(3)+'</small></button>').join('')||'<small>当前显示条件下无关联连线，可降低阈值。</small>';for(const b of $('networkNumbers').querySelectorAll('button'))b.onclick=()=>{const c=counties.find(c=>c.id===b.dataset.neighbor);if(c)selectCounty(c);else{mode='province';selected=null;selectedProv=provinces.find(p=>p.id===b.dataset.neighbor);render();fit();}};}
 $('relationDensity').onchange=e=>{density=e.target.value;renderOverlays();};let thresholdFrame=0;$('relationThreshold').oninput=e=>{threshold=+e.target.value;$('relationThresholdValue').textContent=threshold.toFixed(2);if(!thresholdFrame)thresholdFrame=requestAnimationFrame(()=>{thresholdFrame=0;renderOverlays();});};
 $('networkNav').onclick=()=>{showPage('atlas');$('showLinks').checked=true;renderOverlays();relationship.scrollIntoView({behavior:'smooth',block:'nearest'});};
 $('showLinks').onchange=()=>renderOverlays();$('showReserves').onchange=()=>renderOverlays();
 // Twelve perturbations are diagnostics, not an alternative published ranking.
 const diagnostics=document.createElement('section');diagnostics.className='modelDiagnostics';diagnostics.innerHTML='<div class="sectionHeading"><div><div class="eyebrow">MODEL / 解释边界与稳健性</div><h2>评分、协调、地区关联：三种不同问题</h2></div></div><div class="modelRoles"><div><b>开发优先级</b><p>六指标等权 TOPSIS，回答综合条件相对更有利在哪里。5级最高，等级按全国五分位阈值，每级约20%，同分不拆级。</p></div><div><b>县域耦合协调度</b><p>联合描述县内资源与低碳相关系统。不作为评分输入；缺少必要指标时保持缺失。</p></div><div><b>地区关联</b><p>相似特征与空间接近的组合。用于寻找比较对象，与评分并行；增删连线不改变排名。</p></div></div><div id="robustnessNumbers"></div><p>稳健性诊断：分别将六项权重上调、下调20%，重新归一化权重，沿用现有指标尺度，并重新计算每次全国五分位阈值。只诊断敏感性，不替换已发布的基准得分，也不保证现实选址最优。</p><details><summary>模型还应如何改进？</summary><p>目前等权是透明基准，不是验证出的最优权重。自然潜力含开发规模，与土地、辐射存在指标重叠的可能；应核实其构造后做去重对照。碳强度在这里表示减排需求，不能解读为低碳表现。保护区是空间约束，需在具体地块核查；不能将县域低覆盖率视为开发许可。</p><p>下一阶段应引入实际装机、发电或项目表现做外部验证，检验排序是否有预测价值；空间关联需用不同带宽和邻居数量检验稳定性。缺少这些证据前，不以更复杂算法或更好看的等级宣称模型更优。</p></details>';
 $('modelSection').before(diagnostics);
 function auditModel(){const m=model.priorityRevision,lo=m.low,sp=m.high.map((v,i)=>v-lo[i]),keys=['carbon','land6','land3','slope','gdp','solar'],rows=counties.filter(c=>valid(val(c,'score'))),z=rows.map(c=>keys.map((k,i)=>{const x=(val(c,k)-lo[i])/(sp[i]||1);return m.directions[i]===-1?1-x:x;}));const baseWeights=m.weights,ratios=[];for(let j=0;j<6;j++)for(const factor of [.8,1.2]){const w=baseWeights.map((v,i)=>v*(i===j?factor:1)),sum=w.reduce((a,b)=>a+b,0);w.forEach((v,i)=>w[i]=v/sum);const scenarioScores=z.map(row=>{let near=0,far=0;for(let k=0;k<6;k++){near+=w[k]*(1-row[k])**2;far+=w[k]*row[k]**2;}return Math.sqrt(far)/(Math.sqrt(near)+Math.sqrt(far));});const sorted=[...scenarioScores].sort((a,b)=>a-b),cuts=[.2,.4,.6,.8].map(q=>{const t=q*(sorted.length-1),i=Math.floor(t);return sorted[i]+(sorted[Math.min(i+1,sorted.length-1)]-sorted[i])*(t-i);});let stable=0;for(let i=0;i<rows.length;i++){const g=1+cuts.filter(t=>scenarioScores[i]>t).length;if(g===val(rows[i],'priority'))stable++;}ratios.push(stable/rows.length);}const means=z[0].map((_,j)=>z.reduce((s,r)=>s+r[j],0)/z.length);let peak={r:0,i:0,j:1};for(let i=0;i<6;i++)for(let j=i+1;j<6;j++){let xy=0,xx=0,yy=0;for(const row of z){const x=row[i]-means[i],y=row[j]-means[j];xy+=x*y;xx+=x*x;yy+=y*y;}const r=xy/Math.sqrt(xx*yy);if(Math.abs(r)>Math.abs(peak.r))peak={r,i,j};}const grades=[1,2,3,4,5].map(g=>rows.filter(c=>val(c,'priority')===g).length),biggest=grades.indexOf(Math.max(...grades));const labels=['减排需求','碳汇覆盖','土地可用评分','坡度适宜','经济基础','自然潜力'];const complete=counties.filter(c=>valid(val(c,'coord'))).length;$('robustnessNumbers').innerHTML=[['评分覆盖',rows.length+' / '+counties.length],['协调度覆盖',complete+' / '+counties.length],['权重扰动后等级保持率',(Math.min(...ratios)*100).toFixed(1)+'%–'+(Math.max(...ratios)*100).toFixed(1)+'%'],['最大等级组占比',(biggest+1)+'级 · '+(grades[biggest]/rows.length*100).toFixed(1)+'%'],['最高指标相关性 |r|',Math.abs(peak.r).toFixed(3)],['实际项目外部验证','尚未开展']].map(([k,v])=>'<div><small>'+k+'</small><strong>'+v+'</strong></div>').join('');const extra=document.createElement('p');extra.textContent=labels[peak.i]+' 与 '+labels[peak.j]+' 的评分输入相关系数为 '+peak.r.toFixed(3)+'，应核实土地分类的信息重叠。等级集中在'+(biggest+1)+'级。同分保持同级；分位阈值附近的县可能十分接近，跨级不意味着实际条件突变。请同时比较连续得分。';diagnostics.append(extra);const scoreButton=document.createElement('button');scoreButton.textContent='地图查看连续综合得分 ↗';scoreButton.className='textButton';scoreButton.onclick=()=>{metric='score';for(const b of document.querySelectorAll('[data-metric]'))b.classList.toggle('active',b.dataset.metric===metric);showPage('atlas');render();};diagnostics.append(scoreButton);window.ATLAS_MODEL_DIAGNOSTICS={scenarios:12,minStable:Math.min(...ratios),maxStable:Math.max(...ratios)};}
 function routeHash(){const key=location.hash.slice(1),target=$(key),section=target?.closest('.appPage');showPage(['context','findings'].includes(key)?key:section?.dataset.page||'atlas',false);}
 window.addEventListener('popstate',routeHash);window.addEventListener('hashchange',routeHash);
 auditModel();renderDetail();routeHash();window.ATLAS_DASHBOARD_READY=true;
})();
