'use strict';
(()=>{
 const host=document.querySelector('.modelDiagnostics'),button=document.createElement('button');button.id='openModelLab';button.className='casePrimary';button.textContent='打开决策推演 ↗';host.querySelector('.sectionHeading').append(button);
 const panel=document.createElement('section');panel.id='modelLab';panel.className='modelLab panel';panel.hidden=true;host.after(panel);
 const names=['低位型','偏低型','中位型','偏高型','高位型'],spatialNames=['未通过校正检验','高值集聚','低值集聚','高值离群','低值离群'],spatialColors=['#365c6d','#ffb454','#72a79e','#cf7b72','#88a9d2'];let lab=null,loading=null,weightFrame=0,weightTimer=0,previewScores=null;
 const currentWeights=()=>['resource','economy','lowcarbon'].map(k=>+$('labWeight'+k).value);
 const score=(row,w)=>{const x=[row.resourceAxis,row.economyAxis,row.lowcarbonAxis];if(x.some(v=>!valid(v)))return null;const sum=w.reduce((a,b)=>a+b,0);if(!sum)return null;let good=0,bad=0;for(let i=0;i<3;i++){good+=w[i]/sum*(1-x[i])**2;bad+=w[i]/sum*x[i]**2;}return Math.sqrt(bad)/(Math.sqrt(good)+Math.sqrt(bad));};
 function build(){
  for(const c of counties)Object.assign(c,lab.counties[c.id]);
defs.experimentScore=['偏好匹配度','资源、承接基础与低碳相关状态','index'];defs.scenarioFrequency=['情景入选频率','300组偏好情景 · 非成功概率','percent'];defs.spatialPattern=['空间集聚类型','综合得分 · 局部Moran · FDR校正','category'];
  for(const [k,d] of Object.entries(defs).filter(([k])=>['experimentScore','scenarioFrequency','spatialPattern'].includes(k))){const b=document.createElement('button');b.dataset.metric=k;b.innerHTML='<em>'+String(Object.keys(defs).indexOf(k)+1).padStart(2,'0')+'</em><span>'+d[0]+'</span>';b.onclick=()=>setLayer(k);$('metrics').append(b);}
  const f=fill;fill=function(v){return metric==='spatialPattern'?valid(v)?spatialColors[v]:'url(#missing)':f(v);};
  const displayBefore=display;display=function(v,k=metric,province=false){return k==='spatialPattern'?(valid(v)?spatialNames[v]:'暂无数据'):displayBefore(v,k,province);};
  const map=renderMap;renderMap=function(){map();$('provinceMode').disabled=metric==='spatialPattern';if(['correctedCoord','experimentScore','scenarioFrequency','spatialPattern'].includes(metric)){$('hudMeta').textContent=metric==='spatialPattern'?'研究快照 · 县域分类':metric==='scenarioFrequency'?'单位：% · 默认偏好300组情景':'单位：0–1指数 · 研究快照';document.querySelector('.mapMeaning').textContent=metric==='spatialPattern'?'金色 = 经FDR校正的高值集聚':'多目标决策 · 匹配度与研究优先级含义不同';if(metric==='spatialPattern'){$('legendItems').innerHTML=spatialNames.map((s,i)=>'<span><i style="background:'+spatialColors[i]+'"></i>'+s+'</span>').join('');$('legendNote').textContent='8近邻、999次条件置换、BH校正q≤0.05；非因果识别。';}}};
  panel.innerHTML='<div class="sectionHeading"><div><div class="eyebrow">DECISION STUDIO / 资源、偏好与区域结构</div><h2>县域光伏 · 多目标决策推演</h2><p>调整目标偏好，比较匹配度、候选稳健性与空间集聚。</p></div><button id="closeModelLab">收起 ×</button></div><div class="labTabs" role="tablist">'+['协调类型','偏好推演','空间集聚'].map((s,i)=>'<button role="tab" data-lab-tab="'+i+'">'+s+'</button>').join('')+'</div><div class="labPane" id="labPane0"></div><div class="labPane" id="labPane1"></div><div class="labPane" id="labPane2"></div><div id="labSelected" aria-live="polite"></div><p class="labStatus" id="labStatus"></p><a href="downloads/县域决策数据.csv" download>下载县域决策数据 CSV ↓</a><a href="downloads/决策模型说明.md" download>下载模型与方法说明 ↓</a>';
  const cr=lab.coordination,ex=lab.experiment,sp=lab.spatial;
  $('labPane0').innerHTML='<div class="labNotice">资源与低碳相关两系统通过C、T、D构成结构协调度，K-means将其划分为五种相对类型。综合优先级使用六指标TOPSIS和全国五分位；两类输出分别解释协调状态与相对排序。</div><div class="modelRoles"><div><b>资源系统A</b><p>0.4×辐射 + 0.3×坡度适宜 + 0.2×土地可用 + 0.1×GDP指数。</p></div><div><b>低碳相关系统B</b><p>0.5×(1−碳强度) + 0.3×碳汇占比 + 0.2×(1−用电强度)。</p></div><div><b>结构协调度D</b><p>C=2√(AB)/(A+B)，T=0.6A+0.4B，D=√(CT)。类型不是实际政策绩效测量。</p></div></div><div class="labStats">'+stat('有效县域',cr.samples)+stat('聚类类型数','5')+stat('抽样轮廓系数',cr.kCandidates.find(c=>c.k===5).silhouette.toFixed(3))+stat('初始化稳定性ARI',cr.seedARImin.toFixed(3))+'</div><div class="labClusterBars">'+cr.k5CentersAscending.map((v,i)=>'<div><span>'+names[i]+'</span><i><b style="width:'+(v*100)+'%"></b></i><strong>'+v.toFixed(3)+'</strong><small>'+cr.k5Counts[i]+'县</small></div>').join('')+'</div><p>采用50次初始化、固定随机种子。聚类不要求类型人数相同；五类用于研究解释，不声称它是所有数据下的最优分类数。</p><button data-lab-layer="correctedCoord">地图查看耦合协调度 ↗</button>';
  $('labPane1').innerHTML='<div class="modelRoles"><div><b>资源条件 R</b><p>0.40×辐射 + 0.35×坡度适宜 + 0.25×土地可用；由独立资源指标构成共同刻度。</p></div><div><b>承接基础 E</b><p>log(1+统计优先GDP)，1%–99%分位缩放并截尾；这是承接基础代理，不是电网容量。</p></div><div><b>低碳相关状态 L</b><p>0.50×(1−碳强度) + 0.30×碳汇占比 + 0.20×(1−用电强度)，强度指标按负向处理。</p></div></div><div class="labWeights">'+['resource','economy','lowcarbon'].map((k,i)=>'<label>'+['资源偏好','经济偏好','低碳偏好'][i]+' <output id="labOutput'+k+'">33.3%</output><input id="labWeight'+k+'" type="range" min="1" max="100" value="33"></label>').join('')+'</div><p id="labWeightNote">三组默认等权，拖动可预览；松手更新偏好匹配度。综合优先级表示统一研究评价。</p><div class="labStats">'+stat('偏好情景数',ex.scenarioCount)+stat('候选平均保持率',(ex.experimentTop20RetentionMean*100).toFixed(1)+'%')+stat('稳健候选（频率≥80%）',ex.experimentRobustCandidates+'县')+stat('非支配候选',ex.paretoCandidates+'县')+'</div><p>300组情景把三组权重分别乘以0.8–1.2随机因子后归一化。频率表示在这些偏好下进入前20%的次数占比，不是成功概率。候选保持率衡量偏好变化下选择的一致性，不衡量实际项目准确率。</p><p>非支配候选：不存在另一县在R、E、L上均不差且至少一项更好。它呈现真实权衡，但不是工程许可；还需核查具体地块及电网。</p><div class="labActions"><button data-lab-layer="experimentScore">地图看偏好匹配度 ↗</button><button data-lab-layer="scenarioFrequency">地图看情景入选频率 ↗</button></div>';
  $('labPane2').innerHTML='<div class="labStats">'+stat('全局Moran I',sp.moranI.toFixed(3))+stat('全局置换p值',sp.globalPermutationP.toFixed(3))+stat('高值集聚',sp.patternCounts['1']+'县')+stat('低值集聚',sp.patternCounts['2']+'县')+'</div><p>基于综合研究得分，使用球面距离的8个最近县域质心，行标准化权重。它与“65%相似＋35%接近”的展示网络独立，属于可检验的空间统计。</p><p>局部检验采用999次条件置换，双侧p值做Benjamini–Hochberg多重比较校正，q≤0.05才着色。未通过检验不等于地区没有潜力。高—低或低—高表示空间离群。</p><div class="tableWrap"><table><thead><tr><th>邻居数</th><th>Moran I</th><th>与8邻居象限一致率</th></tr></thead><tbody>'+sp.neighborSensitivity.map(r=>'<tr><td>'+r.neighbors+'</td><td>'+r.moranI.toFixed(3)+'</td><td>'+(r.quadrantAgreementWith8*100).toFixed(1)+'%</td></tr>').join('')+'</tbody></table></div><p>检验发现空间集聚，不证明因果、输电或地区协同收益。近邻是质心距离关系，不等同于行政接壤。</p><button data-lab-layer="spatialPattern">地图看经校正的空间类型 ↗</button>';
  for(const b of panel.querySelectorAll('[data-lab-tab]'))b.onclick=()=>{for(const p of panel.querySelectorAll('.labPane'))p.hidden=p.id!=='labPane'+b.dataset.labTab;for(const t of panel.querySelectorAll('[data-lab-tab]'))t.setAttribute('aria-selected',String(t===b));};panel.querySelector('[data-lab-tab]').click();
  for(const b of panel.querySelectorAll('[data-lab-layer]'))b.onclick=()=>setLayer(b.dataset.labLayer);
  for(const key of ['resource','economy','lowcarbon']){$('labWeight'+key).oninput=()=>{const w=currentWeights(),sum=w.reduce((a,b)=>a+b,0);['resource','economy','lowcarbon'].forEach((k,i)=>$('labOutput'+k).textContent=(w[i]/sum*100).toFixed(1)+'%');updateSelected();clearTimeout(weightTimer);weightTimer=setTimeout(commitWeights,150);};$('labWeight'+key).onchange=commitWeights;}
  $('closeModelLab').onclick=()=>{panel.hidden=true;button.setAttribute('aria-expanded','false');};
  const detail=renderDetail;renderDetail=function(){detail();if(metric==='spatialPattern'){$('rankingTitle').textContent='空间类型 · 示例县域';const rows=counties.filter(c=>(!pid||c.pid===pid)&&c.spatialPattern===(selected?.spatialPattern||1)).slice(0,5);$('ranking').innerHTML=rows.map(c=>'<button class="rank" data-id="'+c.id+'"><span>'+esc(c.name)+'</span><b>'+spatialNames[c.spatialPattern]+'</b></button>').join('');for(const b of $('ranking').querySelectorAll('button'))b.onclick=()=>selectCounty(counties.find(c=>c.id===b.dataset.id));}updateSelected();};updateSelected();
 }
 function stat(k,v){return '<div><small>'+k+'</small><strong>'+v+'</strong></div>';}
 function setLayer(k){if(k==='correctedCoord')k='coord';metric=k;if(k==='spatialPattern'){mode='county';selectedProv=null;}for(const b of document.querySelectorAll('[data-metric]'))b.classList.toggle('active',b.dataset.metric===k);render();$('atlas').scrollIntoView({behavior:'smooth',block:'start'});}
 function updateSelected(){if(!lab||!$('labSelected'))return;const c=selected,row=c&&lab.counties[c.id];if(!c){$('labSelected').textContent='点击地图选择县域，查看三个目标、情景频率和空间类型。';return;}const s=score(row,currentWeights());$('labSelected').innerHTML='<h3>'+esc(c.name)+' · 决策依据</h3><div class="labStats">'+stat('当前偏好匹配度',fmt(s))+stat('耦合协调度',fmt(row.correctedCoord))+stat('情景入选频率',valid(row.scenarioFrequency)?(row.scenarioFrequency*100).toFixed(1)+'%':'输入不足')+stat('空间类型',spatialNames[row.spatialPattern])+'</div><p>R '+fmt(row.resourceAxis)+' · E '+fmt(row.economyAxis)+' · L '+fmt(row.lowcarbonAxis)+'；K-means类型 '+(row.correctedCoordGrade?names[row.correctedCoordGrade-1]:'输入不足')+'；非支配候选 '+(row.pareto===null?'输入不足':row.pareto?'是':'否')+'。情景频率仍基于默认三组等权的300次情景，拖动只改变偏好匹配度。</p>';}
 function commitWeights(){clearTimeout(weightTimer);const w=currentWeights();for(const c of counties)c.experimentScore=score(lab.counties[c.id],w);if(metric==='experimentScore'){mapKey='';render();}updateSelected();$('labWeightNote').textContent='当前偏好匹配度已更新；情景频率依据默认三组等权的300次抽样计算。';}
 button.setAttribute('aria-expanded','false');button.onclick=async()=>{button.disabled=true;button.textContent='正在载入决策数据…';try{if(!lab){loading=loading||Promise.resolve(window.ATLAS_LAB_DATA||loadAtlasAsset(ATLAS_ASSETS.lab));lab=await loading;build();}panel.hidden=false;button.setAttribute('aria-expanded','true');button.textContent='打开决策推演 ↗';panel.scrollIntoView({behavior:'smooth'});window.ATLAS_LAB_READY=true;}catch(e){loading=null;button.textContent='决策数据未加载，点击重试';}finally{button.disabled=false;}};
})();
