'use strict';
(()=>{
 const byId=new Map(counties.map(c=>[c.id,c])),percentCache=new Map();let compareScale='percentile',browse={query:'',province:'',sort:'score_desc',page:1,size:20},candidateRows=[],recent=[];
 try{recent=JSON.parse(localStorage.getItem('atlas-recent-counties')||'[]').filter(id=>byId.has(id)).slice(0,8);}catch{}
 const scientific=v=>{const [a,b]=v.toExponential(2).split('e'),sup={'-':'⁻','+':'','0':'⁰','1':'¹','2':'²','3':'³','4':'⁴','5':'⁵','6':'⁶','7':'⁷','8':'⁸','9':'⁹'};return a+'×10'+String(+b).split('').map(x=>sup[x]).join('');};
 const precise=v=>!valid(v)?'暂无数据':v===0?'0':Math.abs(v)<.00001?scientific(v):Math.abs(v)<.1?String(Number(v.toPrecision(4))):String(Number(v.toFixed(4)));
 const displayBefore=display;display=function(v,k=metric,province=false){if(!valid(v))return '暂无数据';if(k==='priority'||k==='spatialPattern'||isTotal(k)||k==='score')return displayBefore(v,k,province);return defs[k]?.[2]==='percent'?precise(v*100)+'%':precise(v);};
 const percentile=(v,k)=>{if(!valid(v))return null;const key=version+'|'+k;let a=percentCache.get(key);if(!a){a=counties.map(c=>val(c,k)).filter(valid).sort((a,b)=>a-b);percentCache.set(key,a);}if(a.length<2)return 50;let lo=0,hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m]<v)lo=m+1;else hi=m;}const lower=lo;hi=a.length;while(lo<hi){const m=(lo+hi)>>1;if(a[m]<=v)lo=m+1;else hi=m;}return 100*Math.max(0,Math.min(a.length-1,(lower+lo-1)/2))/(a.length-1);};
 const delta=(a,b,k)=>!valid(a)||!valid(b)?'不可比较':(a-b>0?'+':'')+(defs[k]?.[2]==='percent'?precise((a-b)*100)+' 个百分点':isTotal(k)?display(a-b,k):precise(a-b));
 function download(name,data,type='application/json'){const href=URL.createObjectURL(new Blob([data],{type})),link=document.createElement('a');link.href=href;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(href),5000);}
 const remember=id=>{recent=[id,...recent.filter(x=>x!==id)].slice(0,8);try{localStorage.setItem('atlas-recent-counties',JSON.stringify(recent));}catch{}};

 // One collapsed workspace, with the current layer and legend always visible.
 $('map').setAttribute('role','group');
 const mapPanel=document.querySelector('.mapPanel'),controls=document.createElement('details');controls.id='mapControlPanel';controls.className='mapControlPanel';controls.innerHTML='<summary><span id="controlSummary">图层与筛选</span></summary><div class="mapControlContents"></div>';
 const bar=document.createElement('div');bar.className='compactMapBar';bar.append(controls);document.querySelector('.mapHeader').after(bar);
 const contents=controls.querySelector('.mapControlContents');contents.append(document.querySelector('.left'),document.querySelector('.mapFilterRibbon'),document.querySelector('.overlayControls'));
 document.querySelector('.mobileLayers')?.remove();bar.append($('openStudio'));const brief=document.createElement('span');brief.id='filterBrief';bar.append(brief);
 const hud=document.querySelector('.mapHUD');document.querySelector('.mapCanvas').before(hud);
 const detailFold=document.createElement('details');detailFold.className='detailFold';detailFold.open=innerWidth>=1100;detailFold.innerHTML='<summary>地区画像与关联</summary>';const right=document.querySelector('.right');right.before(detailFold);detailFold.append(right);
 function layout(){if(document.body.dataset.page!=='atlas')return;const canvas=document.querySelector('.mapCanvas'),height=Math.max(innerWidth<900?300:340,Math.min(720,innerHeight-canvas.getBoundingClientRect().top-scrollY-18))+'px';if(canvas.style.height!==height)canvas.style.height=height;}
 let briefKey='',briefCount=0;function updateBrief(force=false){const state=ATLAS_FILTERS.getState(),f=state.thresholds,key=JSON.stringify([pid,version,state]);if(force===true||key!==briefKey){briefKey=key;briefCount=ATLAS_FILTERS.getCandidates().length;}const texts={controlSummary:'图层与筛选 · '+defs[metric][0],filterBrief:'辐射≥'+f.sun.toFixed(2)+' · 可用≥'+Math.round(f.land*100)+'% · 保护≤'+Math.round(f.reserve*100)+'%',openStudio:'候选清单 · '+briefCount+'县'};for(const [id,text] of Object.entries(texts))if($(id).textContent!==text)$(id).textContent=text;}
 for(const id of ['sunFilter','landFilter','reserveFilter'])$(id).addEventListener('input',updateBrief);
 controls.addEventListener('toggle',()=>{if(!controls.open){layout();if(!pid&&!selected&&!selectedProv)fit();}});window.addEventListener('resize',()=>requestAnimationFrame(()=>{layout();if(!pid&&!selected&&!selectedProv)fit();}));
 document.addEventListener('click',e=>{if(controls.open&&!controls.contains(e.target))controls.open=false;});

 // Sort by continuous score inside a level; publish actual values and rank.
 let topKey='';function renderRanking(){if(metric==='spatialPattern')return;const key=[mode,pid,selectedProv?.id||'',metric,version].join('|');if(key===topKey)return;topKey=key;const pool=selectedProv&&mode==='province'?provRows(selectedProv):areaRows(),ranked=pool.filter(c=>valid(val(c,metric))).sort((a,b)=>metric==='priority'?val(b,'score')-val(a,'score')||a.id.localeCompare(b.id):val(b,metric)-val(a,metric)||val(b,'score')-val(a,'score')||a.id.localeCompare(b.id)).slice(0,5);
 $('rankingTitle').textContent=metric==='priority'?'高优先级候选 · 按综合得分排序':defs[metric][0]+' · 数值前五';$('ranking').innerHTML=ranked.map(c=>'<button class="rank" data-id="'+c.id+'" aria-label="定位'+esc(c.province+' '+c.name)+'"><span>'+esc(c.name)+'<small>全国第'+c.priorityRank+'位</small></span><b>'+display(val(c,metric),metric)+(metric==='priority'?'<small>得分 '+display(val(c,'score'),'score')+'</small>':'')+'</b></button>').join('');for(const b of $('ranking').querySelectorAll('button'))b.onclick=()=>selectCounty(byId.get(b.dataset.id));}
 window.ATLAS_RANKING_UI=renderRanking;window.addEventListener('atlas:weights-committed',()=>{topKey='';if(metric==='experimentScore')renderRanking();});

 // Histogram retains all observations, with explicit tail bins.
 const distribution=document.querySelector('.distribution');distribution.querySelector('h2').textContent='综合得分分布';distribution.querySelector('.distributionBody').hidden=true;
 const histogram=svg('svg',{id:'scoreHistogram',viewBox:'0 0 400 145',role:'img','aria-label':'综合得分分布直方图，含低值与高值尾部'});distribution.querySelector('.sectionHeading').after(histogram);
 const quantile=(a,q)=>{const t=q*(a.length-1),i=Math.floor(t);return a[i]+(a[Math.min(i+1,a.length-1)]-a[i])*(t-i);};
 let histKey='';function drawHistogram(){const scope=selectedProv&&mode==='province'?selectedProv.id:pid,key=version+'|'+scope+'|'+(selected?.id||'');if(key===histKey)return;histKey=key;const all=counties.map(c=>val(c,'score')).filter(valid).sort((a,b)=>a-b),values=(scope?counties.filter(c=>c.pid===scope):counties).map(c=>val(c,'score')).filter(valid);if(!all.length)return;const low=quantile(all,.01),high=quantile(all,.99),bins=24,counts=new Array(bins+2).fill(0),national=new Array(bins+2).fill(0),bucket=v=>v<low?0:v>high?bins+1:1+Math.min(bins-1,Math.floor((v-low)/Math.max(high-low,1e-12)*bins));values.forEach(v=>counts[bucket(v)]++);all.forEach(v=>national[bucket(v)]++);const maximum=Math.max(...counts.map(c=>c/Math.max(values.length,1)),...national.map(c=>c/all.length)),width=350/counts.length;histogram.replaceChildren();
 for(let i=0;i<counts.length;i++){const height=counts[i]/Math.max(values.length,1)/maximum*85,x=30+i*width;const bar=svg('rect',{x,y:112-height,width:width-2,height,fill:i===0||i===bins+1?'#72a79e':'#d3ba7b'});bar.append(svg('title',{},(i===0?'低值尾部 <'+precise(low):i===bins+1?'高值尾部 >'+precise(high):precise(low+(i-1)*(high-low)/bins)+'–'+precise(low+i*(high-low)/bins))+'：'+counts[i]+'县'));histogram.append(bar);if(scope){const h=national[i]/all.length/maximum*85;histogram.append(svg('path',{d:'M'+x+' '+(112-h)+'h'+(width-2),stroke:'#a3d2de','stroke-width':2}));}}
 histogram.append(svg('text',{x:30,y:132,class:'plotTick'},'尾部'),svg('text',{x:54,y:132,class:'plotTick'},low.toFixed(3)),svg('text',{x:350,y:132,'text-anchor':'end',class:'plotTick'},high.toFixed(3)),svg('text',{x:380,y:132,'text-anchor':'end',class:'plotTick'},'尾部'));
 if(selected){const v=val(selected,'score');if(valid(v)){const x=30+(bucket(v)+.5)*width;histogram.append(svg('path',{d:'M'+x+' 20V114',stroke:'#fff1c7','stroke-width':2}));}}
 $('distributionCount').textContent=values.length+'县';distribution.querySelector('.subtle').textContent=(scope?'金色：当前省份占比；青线：全国占比。':'全国分布；金色为1%–99%区间，两端为区间外县域。')+'完整范围 '+display(all[0],'score')+'–'+display(all.at(-1),'score')+'。';}

 // All candidates stay navigable through query, sorting and pages.
 const toolbar=document.createElement('div');toolbar.className='candidateBrowse';toolbar.innerHTML='<label>搜索候选<input id="candidateSearch" placeholder="县名、代码或省份" type="search"></label><label>省份<select id="candidateProvince"><option value="">全部候选省份</option>'+provinces.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('')+'</select></label><label>排序<select id="candidateSort"><option value="score_desc">综合得分从高到低</option><option value="score_asc">综合得分从低到高</option><option value="radiation_desc">辐射从高到低</option><option value="land_desc">土地可用从高到低</option><option value="protected_asc">保护区占比从低到高</option><option value="coord_desc">协调度从高到低</option></select></label><label>每页<select id="candidateSize"><option>20</option><option>50</option><option>100</option></select></label>';$('candidateNote').before(toolbar);
 const pagination=document.createElement('div');pagination.className='candidatePagination';pagination.innerHTML='<button id="candidatePrev">上一页</button><span id="candidatePage" aria-live="polite"></span><button id="candidateNext">下一页</button><button id="candidateLocateSelected">清单定位地图所选县</button><span id="candidateSelectionStatus" aria-live="polite"></span>';$('candidateRows').closest('.candidateTable').after(pagination);
 let candidateKey='',lastSelection='';function browsed(){const q=browse.query.trim().toLowerCase(),all=ATLAS_FILTERS.getCandidates();return all.filter(c=>(!browse.province||c.pid===browse.province)&&(!q||[c.name,c.id,c.province,c.city].join(' ').toLowerCase().includes(q))).sort((a,b)=>{const [k,direction]=browse.sort.split('_'),value=c=>k==='land'?1-c.land3:val(c,k),av=value(a),bv=value(b);if(!valid(av))return valid(bv)?1:a.id.localeCompare(b.id);if(!valid(bv))return -1;return (direction==='asc'?av-bv:bv-av)||val(b,'score')-val(a,'score')||a.id.localeCompare(b.id);});}
 const highlight=id=>{for(const p of $('regions').querySelectorAll('.candidateLinked'))p.classList.remove('candidateLinked');if(id)$('regions').querySelector('[data-id="'+id+'"]')?.classList.add('candidateLinked');};
 function drawCandidates(){candidateRows=browsed();const pages=Math.max(1,Math.ceil(candidateRows.length/browse.size));browse.page=Math.max(1,Math.min(pages,browse.page));const start=(browse.page-1)*browse.size,visible=candidateRows.slice(start,start+browse.size),key=JSON.stringify([version,browse,...visible.map(c=>c.id)]);
 $('candidateNote').textContent='联合条件满足 '+ATLAS_FILTERS.getCandidates().length+'县；搜索与省份筛选后 '+candidateRows.length+'县。排序和翻页可浏览全部结果，导出包含当前搜索结果。';$('candidatePage').textContent='第 '+browse.page+' / '+pages+' 页 · '+(candidateRows.length?start+1:0)+'–'+Math.min(start+browse.size,candidateRows.length)+' / '+candidateRows.length+'县';$('candidatePrev').disabled=browse.page===1;$('candidateNext').disabled=browse.page===pages;$('exportCandidates').disabled=!candidateRows.length;
 if(key!==candidateKey){candidateKey=key;$('candidateRows').innerHTML=visible.map(c=>'<tr data-county="'+c.id+'"><td><button data-locate="'+c.id+'" aria-label="地图定位'+esc(c.name)+'">'+esc(c.name)+'</button><small>'+esc(c.province)+' · '+c.id+'</small></td><td>'+display(c.radiation,'radiation')+'</td><td>'+display(1-c.land3,'land3')+'</td><td>'+display(c.protected,'protected')+'</td><td>'+display(val(c,'score'),'score')+'</td><td>'+val(c,'priority')+'级</td><td><button data-a="'+c.id+'" aria-label="将'+esc(c.name)+'加入对照A">加入 A</button> <button data-b="'+c.id+'" aria-label="将'+esc(c.name)+'加入对照B">加入 B</button></td></tr>').join('')||'<tr><td colspan="7">当前搜索没有结果，可清空搜索或调整条件。</td></tr>';
 for(const row of $('candidateRows').querySelectorAll('[data-county]')){row.onpointerenter=()=>highlight(row.dataset.county);row.onpointerleave=()=>highlight('');row.onfocusin=()=>highlight(row.dataset.county);row.onfocusout=()=>highlight('');}
 for(const b of $('candidateRows').querySelectorAll('button'))b.onclick=()=>{if(b.dataset.locate){selectCounty(byId.get(b.dataset.locate));$('atlas').scrollIntoView({behavior:'smooth'});}else{const role=b.dataset.a?'A':'B',id=b.dataset.a||b.dataset.b;$('compare'+role).value=id;$('compare'+role).dispatchEvent(new Event('change',{bubbles:true}));b.textContent='已加入 '+role;}};
 }
 syncCandidateSelection();}
 function syncCandidateSelection(reveal=false){const index=selected?candidateRows.findIndex(c=>c.id===selected.id):-1;for(const row of $('candidateRows').querySelectorAll('[data-county]')){const active=row.dataset.county===selected?.id;row.classList.toggle('candidateRowSelected',active);if(active)row.setAttribute('aria-current','true');else row.removeAttribute('aria-current');}$('candidateSelectionStatus').textContent=selected?index>=0?'已联动：'+selected.name:'所选 '+selected.name+' 不在当前搜索候选中':'';if(reveal&&index>=0){browse.page=1+Math.floor(index/browse.size);candidateKey='';drawCandidates();$('candidateRows').querySelector('[data-locate="'+selected.id+'"]')?.focus({preventScroll:true});}}
 window.ATLAS_CANDIDATE_UI=drawCandidates;for(const [id,key] of [['candidateSearch','query'],['candidateProvince','province'],['candidateSort','sort'],['candidateSize','size']])$(id).addEventListener(id==='candidateSearch'?'input':'change',()=>{browse[key]=key==='size'?+$(id).value:$(id).value;browse.page=1;drawCandidates();});$('candidatePrev').onclick=()=>{browse.page--;drawCandidates();};$('candidateNext').onclick=()=>{browse.page++;drawCandidates();};$('candidateLocateSelected').onclick=()=>syncCandidateSelection(true);
 $('exportCandidates').onclick=()=>{drawCandidates();const state=snapshot(),quote=v=>'"'+String(v??'').replaceAll('"','""')+'"',f=state.filters.thresholds,headers=['县代码','县名','省份','综合得分','全国排名','优先级','太阳辐射指数','土地可用程度','保护区覆盖','辐射下限','土地可用下限','保护区上限','资源偏好','经济偏好','低碳偏好','版本','数据快照','导出时间','搜索','省份筛选','框选范围'];const lines=candidateRows.map(c=>[c.id,c.name,c.province,val(c,'score'),c.priorityRank,val(c,'priority'),c.radiation,1-c.land3,c.protected,f.sun,f.land,f.reserve,...state.preference.normalizedWeights,state.appVersion,state.data.core,state.exportedAt,browse.query,browse.province,JSON.stringify(state.filters.brush)]);download('逐光-候选县清单.csv','\uFEFF'+[headers,...lines].map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
 window.ATLAS_CANDIDATES={getRows:()=>browsed(),getState:()=>({...browse}),setState:s=>{browse={...browse,...s};browse.size=[20,50,100].includes(+browse.size)?+browse.size:20;browse.page=Math.max(1,+browse.page||1);for(const [id,k] of [['candidateSearch','query'],['candidateProvince','province'],['candidateSort','sort'],['candidateSize','size']])$(id).value=browse[k];candidateKey='';drawCandidates();}};

 // Searchable A/B comboboxes preserve original select IDs for every action.
 const combos={};function makeCombo(role){const select=$('compare'+role);select.hidden=true;select.tabIndex=-1;select.setAttribute('aria-hidden','true');const box=document.createElement('div');box.className='countyCombo';box.innerHTML='<select id="compareProvince'+role+'" aria-label="对照'+role+'的省份筛选"><option value="">全部省份</option>'+provinces.map(p=>'<option value="'+p.id+'">'+esc(p.name)+'</option>').join('')+'</select><input id="compareSearch'+role+'" role="combobox" aria-label="搜索对照'+role+'县域，可按县名或代码" aria-autocomplete="list" aria-expanded="false" aria-controls="compareSuggestions'+role+'" autocomplete="off"><div id="compareSuggestions'+role+'" class="comboSuggestions" role="listbox" hidden></div><small id="compareMatchCount'+role+'"></small>';select.after(box);const input=$('compareSearch'+role),list=$('compareSuggestions'+role);let choices=[],index=-1;
 const label=c=>c.name+' · '+c.id;function sync(){const c=byId.get(select.value);input.value=c?label(c):'';input.dataset.choice=select.value;}
 function close(){list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');index=-1;}
 function choose(id){select.value=id;remember(id);select.dispatchEvent(new Event('change',{bubbles:true}));sync();close();input.focus({preventScroll:true});}
 function show(){const p=$('compareProvince'+role).value,q=input.value===label(byId.get(select.value))?'':input.value.trim().toLowerCase();const matches=counties.filter(c=>(!p||c.pid===p)&&(!q||[c.name,c.id,c.province].join(' ').toLowerCase().includes(q)));const preferred=[selected?.id,...recent,...ATLAS_FILTERS.getCandidates().map(c=>c.id)],order=new Map([...new Set(preferred.filter(Boolean))].map((id,i)=>[id,i]));matches.sort((a,b)=>(order.get(a.id)??1e6)-(order.get(b.id)??1e6)||val(b,'score')-val(a,'score')||a.id.localeCompare(b.id));choices=matches.slice(0,20);list.innerHTML=choices.map((c,i)=>'<button type="button" role="option" tabindex="-1" id="combo'+role+c.id+'" aria-selected="false" data-county="'+c.id+'">'+esc(c.name)+'<small>'+esc(c.province)+' · '+c.id+(c.id===selected?.id?' · 地图所选':recent.includes(c.id)?' · 最近使用':'')+'</small></button>').join('')||'<span>未找到匹配县域</span>';$('compareMatchCount'+role).textContent=matches.length+'个匹配 · 先显示地图所选、最近使用及当前候选';list.hidden=false;input.setAttribute('aria-expanded','true');index=-1;for(const b of list.querySelectorAll('button')){b.onpointerdown=e=>e.preventDefault();b.onclick=()=>choose(b.dataset.county);}}
 input.oninput=show;input.onfocus=()=>{input.select();show();};input.onkeydown=e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();if(list.hidden)show();index=e.key==='Home'?0:e.key==='End'?choices.length-1:Math.max(0,Math.min(choices.length-1,index+(e.key==='ArrowDown'?1:-1)));for(const b of list.querySelectorAll('button'))b.setAttribute('aria-selected',String(b.dataset.county===choices[index]?.id));if(choices[index]){input.setAttribute('aria-activedescendant','combo'+role+choices[index].id);$('combo'+role+choices[index].id).scrollIntoView({block:'nearest'});}}else if(e.key==='Enter'&&!list.hidden){e.preventDefault();if(choices[index>=0?index:0])choose(choices[index>=0?index:0].id);}else if(e.key==='Escape'){close();sync();}else if(e.key==='Tab')close();};input.onblur=()=>setTimeout(()=>{if(!box.contains(document.activeElement)){close();sync();}},100);$('compareProvince'+role).onchange=show;select.onchange=()=>renderComparison();combos[role]={sync,close};sync();}
 makeCombo('A');makeCombo('B');
 const scaleButtons=document.createElement('div');scaleButtons.className='comparisonScale';scaleButtons.innerHTML='<span>条形刻度</span><button data-compare-scale="raw" aria-pressed="false">指标值 · 原刻度</button><button data-compare-scale="percentile" aria-pressed="true">全国分位 · 共同0–100</button><small>数值始终显示原刻度；差值按原单位计算</small>';$('comparisonBars').before(scaleButtons);
 const comparisonBefore=renderComparison;renderComparison=function(){comparisonBefore();const a=byId.get($('compareA').value),b=byId.get($('compareB').value);if(!a||!b)return;$('comparisonBars').innerHTML=comparisonMetrics.map(k=>{const av=val(a,k),bv=val(b,k),ap=percentile(av,k),bp=percentile(bv,k),scale=v=>compareScale==='percentile'?percentile(v,k):valid(v)?Math.max(0,Math.min(1,v/compareMax[k]))*100:0;return '<div class="compareMetric"><div><b>'+defs[k][0]+'</b><small>'+defs[k][1]+'</small></div><div class="doubleTrack">'+[[av,ap,'A'],[bv,bp,'B']].map(([v,p,r])=>'<div><i style="width:'+(scale(v)||0)+'%"></i><span>'+r+' '+display(v,k)+'<small>全国分位 '+(valid(p)?p.toFixed(1):'—')+'</small></span></div>').join('')+'</div><span class="metricDelta">A − B<br>'+delta(av,bv,k)+'</span></div>';}).join('');$('comparisonSource').textContent='GDP来源：A '+(a.gdpHybridSource||'未记录')+'；B '+(b.gdpHybridSource||'未记录')+'。全国分位使用全国有效县域，同分取平均位置；原刻度模式各指标使用固定全国共同标尺，不随A/B组合拉伸。指标值可能为归一化指数，百分比差值以“个百分点”表示。';for(const b of scaleButtons.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.compareScale===compareScale));combos.A.sync();combos.B.sync();};for(const b of scaleButtons.querySelectorAll('button'))b.onclick=()=>{compareScale=b.dataset.compareScale;renderComparison();};

 // Roving SVG focus plus accessible table and combobox alternatives.
 const describePath=p=>{const c=regionById.get(p.dataset.id);if(c)p.setAttribute('aria-label',c.name+'，'+defs[metric][0]+' '+display(mapValue(c),metric,mode==='province')+'；按回车查看详情');};
 let decorated=null;function accessibleMap(){const group=$('regions');group.setAttribute('aria-label',defs[metric][0]+'；方向键选择地区，回车查看详情');if(decorated!==group.firstChild){decorated=group.firstChild;const id=mode==='county'?selected?.id||areaRows()[0]?.id:selectedProv?.id||provinces[0]?.id;for(const p of group.children){if(p.getAttribute('role')==='button')continue;const c=regionById.get(p.dataset.id);p.setAttribute('tabindex',p.dataset.id===id?'0':'-1');p.setAttribute('role','button');p.setAttribute('aria-label',c.name+'；按回车查看详情');}}if(group.contains(document.activeElement)&&document.activeElement.matches('path'))describePath(document.activeElement);}
 $('regions').addEventListener('focusin',e=>{if(e.target.matches('path'))describePath(e.target);});
 $('regions').addEventListener('keydown',e=>{const p=e.target.closest('[data-id]');if(!p)return;if(e.key==='Enter'||e.key===' '){e.preventDefault();p.dispatchEvent(new MouseEvent('click',{bubbles:true}));return;}if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(e.key))return;e.preventDefault();const pool=(mode==='county'?areaRows():provinces),from=pool.find(c=>c.id===p.dataset.id);let next;if(e.key==='Home')next=pool[0];else if(e.key==='End')next=pool.at(-1);else{const axis=e.key==='ArrowLeft'||e.key==='ArrowRight'?0:1,sign=e.key==='ArrowRight'||e.key==='ArrowDown'?1:-1;next=pool.filter(c=>c.id!==from.id&&(c.center[axis]-from.center[axis])*sign>0).sort((a,b)=>{const cost=c=>{const dx=c.center[0]-from.center[0],dy=c.center[1]-from.center[1],ahead=(c.center[axis]-from.center[axis])*sign;return (dx*dx+dy*dy)/ahead;};return cost(a)-cost(b);})[0];}if(next){p.setAttribute('tabindex','-1');const q=$('regions').querySelector('[data-id="'+next.id+'"]');q?.setAttribute('tabindex','0');q?.focus();}});
 let detailSelection='';const detailBefore=renderDetail;renderDetail=function(){detailBefore();const focus=selected?.id||selectedProv?.id||'';if(focus&&focus!==detailSelection)detailFold.open=true;detailSelection=focus;renderRanking();if(selected&&selected.id!==lastSelection){lastSelection=selected.id;remember(selected.id);if(!$('analysisStudio').hidden){candidateRows=browsed();syncCandidateSelection(true);}}else syncCandidateSelection();for(const p of $('regions').querySelectorAll('[tabindex="0"]'))if(selected&&p.dataset.id!==selected.id)p.setAttribute('tabindex','-1');if(selected)$('regions').querySelector('[data-id="'+selected.id+'"]')?.setAttribute('tabindex','0');drawHistogram();};
 const mapBefore=renderMap;renderMap=function(){mapBefore();accessibleMap();updateBrief();};const statsBefore=renderStats;renderStats=function(){statsBefore();drawHistogram();};

 // Current preference and default-weight robustness are labelled separately.
 function labelPreference(){if(!window.ATLAS_LAB_READY)return;const p=$('labPane1');if(p&&!$('defaultRobustnessLabel')){const fixed=document.createElement('div');fixed.id='defaultRobustnessLabel';fixed.className='fixedScenarioLabel';fixed.textContent='默认等权稳健性 · 固定300组情景 · 不随当前滑块变化';p.querySelector('.labStats').before(fixed);const active=document.createElement('strong');active.className='currentPreferenceLabel';active.textContent='当前偏好方案 · 下方滑块仅更新偏好匹配度';p.querySelector('.labWeights').before(active);}
 if($('labSelected')){const first=$('labSelected').querySelector('.labStats>div:first-child');first?.classList.add('currentPreferenceStat');for(const tile of $('labSelected').querySelectorAll('.labStats>div'))if(tile.textContent.includes('情景入选频率')){tile.classList.add('fixedPreferenceStat');tile.querySelector('small').textContent='默认等权情景入选频率';}}}
 window.addEventListener('atlas:lab-ready',labelPreference);window.addEventListener('atlas:weights-committed',labelPreference);

 const stateTools=document.createElement('div');stateTools.className='analysisStateTools';stateTools.innerHTML='<button id="saveAnalysisState">导出分析状态 ↓</button><button id="loadAnalysisState">恢复分析状态 ↑</button><button id="shareAnalysisState">复制当前分析链接</button><input type="file" id="analysisStateFile" accept=".json,application/json" hidden><span id="analysisStateStatus" role="status"></span>';document.querySelector('.selectionActions').after(stateTools);
 function snapshot(){return {schema:1,appVersion:'v22',ui:{controlsOpen:$('mapControlPanel').open,detailsOpen:document.querySelector('.detailFold').open,candidatesOpen:!$('analysisStudio').hidden,preferenceOpen:!!$('modelLab')&&!$('modelLab').hidden},data:{core:ATLAS_ASSETS.core.url,lab:ATLAS_ASSETS.lab?.url},exportedAt:new Date().toISOString(),page:document.body.dataset.page,metric,version,selection:{county:selected?.id||null,province:selectedProv?.id||null,pid,mode},view:[...view],filters:ATLAS_FILTERS.getState(),candidates:{...browse},comparison:{A:$('compareA').value,B:$('compareB').value,scale:compareScale,provinceA:$('compareProvinceA').value,provinceB:$('compareProvinceB').value,recent:[...recent]},preference:{loaded:!!window.ATLAS_LAB_READY,weights:window.ATLAS_LAB_CONTROLS?.getWeights()||[33,33,33],normalizedWeights:(window.ATLAS_LAB_CONTROLS?.getWeights()||[33,33,33]).map((v,i,a)=>v/a.reduce((s,x)=>s+x,0)),tab:$('modelLab')?.querySelector('[aria-selected="true"]')?.dataset.labTab||'0'},layers:{links:$('showLinks').checked,reserves:$('showReserves').checked,protectedView,density:$('relationDensity').value,threshold:+$('relationThreshold').value}};}
 async function restore(s){if(!s||s.schema!==1||!byId.has(s.comparison?.A)||!byId.has(s.comparison?.B))throw Error('文件不是有效的逐光分析状态');if(s.data?.core!==ATLAS_ASSETS.core.url||(s.preference?.loaded&&s.data?.lab!==ATLAS_ASSETS.lab?.url))throw Error('数据快照不同，无法保证复现；请使用当前版本导出的状态');if(s.preference?.loaded||['experimentScore','scenarioFrequency','spatialPattern'].includes(s.metric)){await $('openModelLab').onclick();if(!window.ATLAS_LAB_READY)throw Error('决策数据尚未载入，无法恢复偏好条件，请重试');}if(!defs[s.metric])throw Error('状态中的图层不可用');version='hybrid';pid=provinces.some(p=>p.id===s.selection.pid)?s.selection.pid:'';mode=s.selection.mode==='province'?'province':'county';selected=byId.get(s.selection.county)||null;selectedProv=provinces.find(p=>p.id===s.selection.province)||null;metric=s.metric;$('province').value=pid;protectedView=s.layers?.protectedView==='coverage'?'coverage':'footprint';$('showLinks').checked=!!s.layers?.links;$('showReserves').checked=!!s.layers?.reserves;$('relationDensity').value=s.layers?.density||'overview';$('relationDensity').dispatchEvent(new Event('change'));$('relationThreshold').value=s.layers?.threshold||0;$('relationThreshold').dispatchEvent(new Event('input'));ATLAS_FILTERS.setState(s.filters||{});ATLAS_CANDIDATES.setState(s.candidates||{});compareScale=s.comparison.scale==='raw'?'raw':'percentile';recent=(s.comparison.recent||[]).filter(id=>byId.has(id)).slice(0,8);for(const r of ['A','B']){$('compare'+r).value=s.comparison[r];$('compareProvince'+r).value=s.comparison['province'+r]||'';$('compare'+r).dispatchEvent(new Event('change',{bubbles:true}));}if(window.ATLAS_LAB_CONTROLS&&s.preference?.loaded){ATLAS_LAB_CONTROLS.setWeights(s.preference.weights);$('modelLab').querySelector('[data-lab-tab="'+s.preference.tab+'"]')?.click();}document.querySelector('[data-page-link="'+(s.page||'atlas')+'"]')?.click();render();await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);layout();if(Array.isArray(s.view)&&s.view.length===4&&s.view.every(valid)&&s.view[2]>0&&s.view[3]>0){view=[...s.view];setView();}for(const b of document.querySelectorAll('[data-metric]'))b.classList.toggle('active',b.dataset.metric===metric);renderComparison();labelPreference();if(s.ui){$('mapControlPanel').open=!!s.ui.controlsOpen;document.querySelector('.detailFold').open=!!s.ui.detailsOpen;$('analysisStudio').hidden=!s.ui.candidatesOpen;if($('modelLab'))$('modelLab').hidden=!s.ui.preferenceOpen;}$('analysisStateStatus').textContent='已恢复图层、范围、筛选、对照、偏好权重与地图视图。';}
 $('saveAnalysisState').onclick=()=>download('逐光-分析状态.json',JSON.stringify(snapshot(),null,2));$('loadAnalysisState').onclick=()=>$('analysisStateFile').click();$('analysisStateFile').onchange=async()=>{try{await restore(JSON.parse(await $('analysisStateFile').files[0].text()));}catch(e){$('analysisStateStatus').textContent=e.message;}};
 const encode=async s=>{const bytes=new TextEncoder().encode(JSON.stringify(s)),compressed=typeof CompressionStream==='function'?new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new CompressionStream('deflate'))).arrayBuffer()):bytes;return (typeof CompressionStream==='function'?'z':'j')+btoa(String.fromCharCode(...compressed)).replaceAll('+','-').replaceAll('/','_').replace(/=+$/,'');};
 const decode=async str=>{const code=str.slice(1).replaceAll('-','+').replaceAll('_','/'),bytes=Uint8Array.from(atob(code),c=>c.charCodeAt(0)),data=str[0]==='z'?new Uint8Array(await new Response(new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer()):bytes;return JSON.parse(new TextDecoder().decode(data));};
 $('shareAnalysisState').onclick=async()=>{if(location.protocol==='file:'){$('analysisStateStatus').textContent='离线版请导出分析状态文件分享。';return;}try{const url=new URL(location.href);url.hash='state='+await encode(snapshot());await navigator.clipboard.writeText(url.href);$('analysisStateStatus').textContent='已复制包含当前分析条件的公开链接。';}catch{$('analysisStateStatus').textContent='复制未完成，请导出分析状态文件。';}};
 $('downloadCompare').onclick=()=>{const s=snapshot(),a=byId.get(s.comparison.A),b=byId.get(s.comparison.B),quote=v=>'"'+String(v??'').replaceAll('"','""')+'"',headers=['县代码','县名','指标','指标值','全国分位','差值A减B','差值单位','条形模式','版本','数据快照','导出时间','资源偏好','经济偏好','低碳偏好','筛选条件'];const rows=[a,b].flatMap(c=>comparisonMetrics.map(k=>[c.id,c.name,defs[k][0],val(c,k),percentile(val(c,k),k),valid(val(a,k))&&valid(val(b,k))?(val(a,k)-val(b,k))*(defs[k][2]==='percent'?100:1):null,defs[k][2]==='percent'?'个百分点':isTotal(k)?totalUnit(k):'指数',compareScale,s.appVersion,s.data.core,s.exportedAt,...s.preference.normalizedWeights,JSON.stringify(s.filters)]));download('逐光-县域对照-'+a.id+'-'+b.id+'.csv','\uFEFF'+[headers,...rows].map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
 document.addEventListener('click',e=>{const link=e.target.closest('a[href]');if(!link||!link.getAttribute('href').endsWith('/县域决策数据.csv')||!window.ATLAS_LAB_READY)return;e.preventDefault();const s=snapshot(),ids=new Set(browsed().map(c=>c.id)),quote=v=>'"'+String(v??'').replaceAll('"','""')+'"',header=['县代码','县名','当前偏好匹配度','资源条件','承接基础','低碳相关状态','默认等权情景入选频率','频率定义','非支配候选','空间类型','资源权重','经济权重','低碳权重','筛选条件','是否当前候选','版本','数据快照','模型快照','导出时间'];const rows=counties.map(c=>[c.id,c.name,c.experimentScore,c.resourceAxis,c.economyAxis,c.lowcarbonAxis,c.scenarioFrequency,'默认等权300组情景；不随滑块改变',c.pareto,c.spatialPattern,...s.preference.normalizedWeights,JSON.stringify(s.filters),ids.has(c.id),s.appVersion,s.data.core,s.data.lab,s.exportedAt]);download('逐光-当前决策数据.csv','\uFEFF'+[header,...rows].map(r=>r.map(quote).join(',')).join('\r\n'),'text/csv;charset=utf-8');},true);
window.ATLAS_ANALYSIS_STATE={snapshot,restore,encode,decode};window.addEventListener('atlas:filters-changed',()=>{updateBrief();if(!$('analysisStudio').hidden)drawCandidates();});
 renderComparison();drawCandidates();renderDetail();accessibleMap();updateBrief();requestAnimationFrame(()=>{layout();fit();});if(location.hash.startsWith('#state='))decode(location.hash.slice(7)).then(restore).catch(e=>$('analysisStateStatus').textContent=e.message);window.ATLAS_USABILITY_READY=true;
})();
